### ISSUE TITLE
Hide precipiation object crashes Torque

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1044]
If you place a precipiation object in your mission, like rain and then try to hide it, so that it does not render anymore, Torque crashes completely.

**Comment by eightyeight** [comment]
@Duion I can't reproduce this in Ubuntu using the default HeavyRain datablock. Will try on Windows soon.

**Comment by eightyeight** [comment]
Reproduced in Windows when right-clicking the object in the editor tree and selecting 'hidden' from there.
