### ISSUE TITLE
GUI Editor moveSelection

### ISSUE THREAD

**Issue by Packer** [GarageGames/Torque3D#1097]
Currently in the development branch moveSelection (Or Nudging in the F10 GUI Editor) is broken, its getting 4 variables when it only wants 3, I looked into it and the moveSelection is only taking the first variable in the engine.

Engine\source\gui\editor\guiEditCtrl.cpp

New broken code:
DefineConsoleMethod( GuiEditCtrl, moveSelection, void, (Point2I pos), , "Move all controls in the selection by (dx,dy) pixels.")
{
   object->moveAndSnapSelection(Point2I(pos));
}
Old Working Code:
ConsoleMethod( GuiEditCtrl, moveSelection, void, 4, 4, "(int dx, int dy) - Move all controls in the selection by (dx,dy) pixels.")
{
   object->moveAndSnapSelection(Point2I(dAtoi(argv[2]), dAtoi(argv[3])));
}

**Comment by eightyeight** [comment]
Ah dear, this was because of #1072 (specifically, [this](https://github.com/GarageGames/Torque3D/pull/1072/files#diff-31f1c0405d8de716887f21a5661307a1L2594)). @Winterleaf changed some APIs which I haven't been diligent enough in checking. Thanks for the report, this will be an easy fix.
