### ISSUE TITLE
OpenGL basic lighting no shadows on player

### ISSUE THREAD

**Issue by JeffProgrammer** [GarageGames/Torque3D#1098]
Running basic lighting in OpenGL currently has no shadow for the player.  I'm assuming its something with the decals since it's a decal based shadow effect?

**Comment by JeffProgrammer** [comment]
I should also point out that regular decals like footprints and bullet shots renders fine.

**Comment by JeffProgrammer** [comment]
I did some code tracing. It is going through the shadow renderer and from what I can tell, it should be casting shadows. I haven't looked at the shader yet. Still do not know why this is happening.

**Comment by LuisAntonRebollo** [comment]
Fixed on #1203

@JeffProgrammer, can you test plz?

**Comment by JeffProgrammer** [comment]
:+1: works. I'll close the issue.
