### ISSUE TITLE
WorldEditor, texture is lost.T3D 3.6.2

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1101]
I do a terrain, save, a then close, open again I keep working, save second time, open again and is a mess, I don't know what happen.

![1](https://cloud.githubusercontent.com/assets/1057449/5696541/7055e9ea-999a-11e4-8850-7c8dc01a9394.JPG)
![2](https://cloud.githubusercontent.com/assets/1057449/5696542/788a310c-999a-11e4-9000-02dd5919122f.JPG)
![4](https://cloud.githubusercontent.com/assets/1057449/5696557/bfe937fa-999a-11e4-8caa-5b20822f575a.JPG)

When I chose Sketch tool, this happens.

![3](https://cloud.githubusercontent.com/assets/1057449/5696562/d5bf9538-999a-11e4-897c-7bffd9410e79.JPG)

Sorry but I don't know how to replicate this.

I can upload my project 557MB.

**Comment by John3** [comment]
When I change to Basic Lighting is completely dark on advanced lighting it like screenshot above. I don't have texture when I hit play.

Sorry I forget to upload the console log

![5](https://cloud.githubusercontent.com/assets/1057449/5696640/f662df32-999c-11e4-8bcd-797dfdaca689.JPG)
![6](https://cloud.githubusercontent.com/assets/1057449/5696642/010ef47a-999d-11e4-99b8-66f65cc921da.JPG)

**Comment by John3** [comment]
I know what happened, shame on me, in some point I forgot to add a Sky... Now everything is as before. Sorry!

**Comment by eightyeight** [comment]
No worries :)
