### ISSUE TITLE
Reduce duplication in script templates

### ISSUE THREAD

**Issue by eightyeight** [GarageGames/Torque3D#1112]
As per [this forum thread](http://www.garagegames.com/community/forums/viewthread/140846), we will introduce a Packages folder to split duplicated script modules into single locations. For example, where we now have something like:

    Templates/
        Full/
            tools/
        Empty/
            tools/

This change will result in:

    Templates/
        Full/
        Empty/
    Packages/
        Editor/
            tools/

When a project is created, desired packages are copied into the project directory the same way templates currently are. This means that instead of changing template scripts in two locations, the package can be changed, and all templates will benefit from the update.

This change will be fully backwards-compatible with 3.6 at the project level - i.e. a project created in 3.7 will look identical to a project created in 3.6. However, user modifications to the templates will have to be ported to the appropriate package.

For associated project generator changes, and an explanation of how templates specify which packages they need, see GarageGames/Torque3D-ProjectManager#36.

The major downside to this change will be that CMake does not currently handle the `template.xml` parsing and file copying needed to replace the work the project generator will do. We view this tradeoff as acceptable; CMake is still pretty much an 'experienced-users-only' option at the moment, and we're sure they can handle a couple of extra copy/pastes when creating a new project. Eventually, CMake will not be responsible for anything to do with the templates, anyway.

**Comment by LuisAntonRebollo** [comment]
:+1:

**Comment by eightyeight** [comment]
Sigh :(

**Comment by Areloch** [comment]
The new template will largely take care of this.
