### ISSUE TITLE
OpenGL bug - removing diffuse from a skybox cause shadergen error

### ISSUE THREAD

**Issue by Lopuska** [GarageGames/Torque3D#1117]
The problem is caused because 'attn' for some reason is a float (scalar) when we don't have diffuse.
so during acess of -> 'float.xxxx' we get an error.

I fixed that changing this:   

```cpp
  {
      if ( attn )
         lerpVal = new GenOp( "saturate( @ ).xxxx", attn );
      else
         blendOp = Material::Mul;
   }
```
to:

```cpp
   {
      if ( attn && fd.materialFeatures.hasFeature( MFT_DiffuseMap ) )
         lerpVal = new GenOp( "saturate( @ ).xxxx", attn );
      else
         blendOp = Material::Mul;
   }
```

**Comment by Lopuska** [comment]
According to Luis, the correct fix is:

lerpVal = new GenOp( "vec4( saturate( @ ) ).xxxx", attn );

Since swizzles in opengl are only supported on non scalar type.
I make a PR for it. Fixed.

**Comment by LuisAntonRebollo** [comment]
Confirmed the problem and fix.

Thx :+1:
