### ISSUE TITLE
Terrain Culling gives better FPS off than on

### ISSUE THREAD

**Issue by chieling** [GarageGames/Torque3D#1120]
per post:
http://www.garagegames.com/community/forums/viewthread/141164

when you turn OFF terrain culling, you get an extra 5-10 FPS. other people in the post are saying that there are known issues with this.

**Comment by rextimmy** [comment]
The problem currently is the terrain occlusion seems to take longer to perform than it does to just render whatever it is that is hidden by the terrain. If you have a reasonably flat terrain than the terrain occlusion test will most likely be pointless and yes actually cost you frame rate. If you have a fairly hilly terrain where a lot of objects would actually be hidden by the terrain than it will become more worthwhile to perform this test.

**Comment by chieling** [comment]
well, we had a very hilly section on our map and that's why this was enabled and we noticed it. From what Im understanding the math (or technique) for this needs revisited.

**Comment by eightyeight** [comment]
A good intermediate solution might be a `#define` allowing you to disable it entirely if you don't feel it adds value to your game.

**Comment by rextimmy** [comment]
sceneCullingState.cpp line 39 (bool SceneCullingState::smDisableTerrainOcclusion = false;). Maybe it would be better to set this to true so that way it's disabled by default and people that do want to use have to opt in.

**Comment by chieling** [comment]
there is no way to set that on a switch so that the users can make the call
to use it or not? otherwise, how will they even know its an option?

On Thu, Feb 19, 2015 at 8:11 AM, Tim <notifications@github.com> wrote:

> sceneCullingState.cpp line 39 (bool
> SceneCullingState::smDisableTerrainOcclusion = false;). Maybe it would be
> better to set this to true so that way it's disabled by default and people
> that do want to use have to opt in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GarageGames/Torque3D/issues/1120#issuecomment-75049268>
> .
>



-- 

Paul Yoskowitz
[image: http://]about.me/paulyoskowitz
<http://about.me/paulyoskowitz?promo=email_sig>

**Comment by andr3wmac** [comment]
Maybe we should add a flag in SceneObject "occluder" or something to that extent. Then in functions like the terrain culling, only test objects that are flagged as occluders. A big problem with the terrain occlusion system is spending more time figuring out if you can draw something than it would take to just draw it.
