### ISSUE TITLE
OpenGL Basic Lighting rendering issues

### ISSUE THREAD

**Issue by JeffProgrammer** [GarageGames/Torque3D#1127]
![](http://i.imgur.com/i66OfDc.jpg)

ew. I suspect something with glowing?

**Comment by JeffProgrammer** [comment]
I replaced the road texture with one from @Azaezel and all the glowing problems went away with both road and water...

**Comment by JeffProgrammer** [comment]
i need to check to see if current fixes in opengl have fixed this issue...

**Comment by JeffProgrammer** [comment]
Still happening.
![](http://i.imgur.com/EBuLCPj.png)

**Comment by JeffProgrammer** [comment]
OKAY, SO GET THIS ONE FOLKS.

I ran cleanShaders.bat and it goes away....renders fine in BL on GL:

![](http://i.imgur.com/e9qlePr.jpg)

**Comment by eightyeight** [comment]
If by fine you mean 'it's night on the land and day at sea' :joy:

**Comment by LuisAntonRebollo** [comment]
@JeffProgrammer , can you compare x64 and x86 builds?

Here i get the problem in x64 only :(

**Comment by LuisAntonRebollo** [comment]
I have fixed a problem with basic water and HDR.

@JeffProgrammer, can you retest?
