### ISSUE TITLE
Pull Request #1026 broke the console stack

### ISSUE THREAD

**Issue by jamesu** [GarageGames/Torque3D#1134]
There have been numerous reports that the console stack is throwing out asserts in the development branch. I've tracked it down to a certain pull request of mine, PR 1026 (https://github.com/GarageGames/Torque3D/pull/1026). Intended to fix issue #976 .

It seems while it fixed the reported issue, it has the unintended side-effect of not cleaning the stack out correctly during future function calls.

**Comment by jamesu** [comment]
I have a preliminary fix for this which resolves this by changing the stack behaviour of executef and the callback helpers (i.e. it makes them all go through templates which properly manage the stack). I'd like to write some basic tests however to ensure the new behaviour isn't breaking anything...

**Comment by eightyeight** [comment]
Is there a consistent way to repro this? At the moment my way of testing it will just involve playing around with the engine to make sure nothing looks broken :P. Are there any unit tests among those you've added that fail before, and pass after the PR?

**Comment by jamesu** [comment]
There are unit tests now for the execute stack handling.

ATM Most stuff works with the new code, the problem I guess is some minor things handle console stack values strangely which don't have tests and thus need to manually be tested...

**Comment by eightyeight** [comment]
Yeah, such as that `dFree` bug earlier. This is why we want to have a pre-release :joy:

**Comment by jamesu** [comment]
It looks like there is a problem with the string iterators. Looks a bit messy, will see if I can work around it.

**Comment by jamesu** [comment]
Should be noted that using dIsSpace is a pretty bad idea here as on some platforms the behavior will change depending on locale settings.

**Comment by jamesu** [comment]
Looks like startsWith is somehow corrupting the value in the string buffer. VERY strange.

**Comment by jamesu** [comment]
Upon further investigation it seems the console stack is getting resized WHILE the string iterator is being used, causing invalid pointers. Gonna have to wrap up that pointer with a helper class so it is offset from the correct position.

**Comment by jamesu** [comment]
Pushed a fix for this which uses a relative pointer type. In addition I've added a new console variable type which acts as a pointer to a stack string which should help reduce the overall stack size (by reusing the data in the previous frames of the stack).

**Comment by eightyeight** [comment]
![](http://upload.wikimedia.org/wikipedia/commons/4/47/River_terrapin.jpg)

Will test soon.
