### ISSUE TITLE
Object editor lod alteration fails

### ISSUE THREAD

**Issue by Azaezel** [GarageGames/Torque3D#1135]
http://i.imgur.com/c6npZqc.jpg

GuiTreeViewCtrl::getItemValue: invalid item id!
TSShapeConstructor::getMeshType: Could not find mesh 'detail3'
TSShapeConstructor::getObjectNode: Could not find object 'detail'
TSShape::setMeshSize: Could not find mesh 'detail 3'

This is both with, and without attempting to resolve via the suggested reversion https://github.com/GarageGames/Torque3D/issues/1134

**Comment by jamesu** [comment]
Does it work before the revision?

**Comment by Azaezel** [comment]
nope. same error either way.

**Comment by jamesu** [comment]
Ok just checking if I broke anything ;)

**Comment by LuisAntonRebollo** [comment]
@Azaezel , can you test if this PR #1246 is correct?

Fixes error msg and looks a correct fix, but not sure.
