### ISSUE TITLE
Bullet build is broken by linux changes

### ISSUE THREAD

**Issue by dragutux** [GarageGames/Torque3D#1136]
removing stdint.h fix the problems but basically https://github.com/GarageGames/Torque3D/commit/4e9034854d057f745f7449502cbad03a3fe8b76e#diff-637773112ccf1788179bc28c358075e0R26 create a redefinition of uint64 for bullet!

**Comment by dragutux** [comment]
PR coming with a proper fix (using a define from bullet)

**Comment by LuisAntonRebollo** [comment]
Thx for report this problem :)

```stdint.h``` is a standart library supported on VS2010, the only problem is we need to configure Bullet library.

I think use T3D header entry point for Bullet is better to place the fix, for avoid add library code to a general header.

**Comment by dragutux** [comment]
err where exactly ?

**Comment by LuisAntonRebollo** [comment]
Fixed on #1146

**Comment by LuisAntonRebollo** [comment]
Fixed and merged on Fix Bullet compilation. #1198
