### ISSUE TITLE
Fix all initializer list ordering

### ISSUE THREAD

**Issue by crabmusket** [GarageGames/Torque3D#1150]
There are a ton of warnings generated by `gcc`'s `-Wreorder`. The warning's meaning is explained [here](http://blog.kutny.net/2014/07/14/c-member-initializer-list-fallacy-a-k-a-wreorder/). Might not be any actual bugs, but it'd be nice to be on the safe side.

**Comment by raistlin** [comment]
I have seen that there are a lot of -Wreorder warnings generated inside /lib/ files.
I think that is not a good idea to modify this files directly, because they will be overwritten if we update these libraries in future.

What do you think?

**Comment by dottools** [comment]
Yeah, third party libraries shouldn't be modified unless absolutely necessary to integrate with the engine that otherwise wouldn't be useable.

**Comment by eightyeight** [comment]
What @dottools said. I've mentioned before the possibility of using git submodules for our lib dependencies, at least those of them for which that's feasible - in that case maybe we could contribute back to those dependencies, maybe fix some warnings, etc. But that might not be a realistic ideal :p.
