### ISSUE TITLE
va_start() without va_end()

### ISSUE THREAD

**Issue by Alex-doc** [GarageGames/Torque3D#1152]
There are some va_start() without a va_end()

https://github.com/GarageGames/Torque3D/blob/4e52824a42108367951c4af77ffd08e979a0b86c/Engine/source/console/console.cpp#L1159

some from:
https://github.com/GarageGames/Torque3D/blob/development/Engine/source/core/strings/stringFunctions.cpp#L387

https://github.com/GarageGames/Torque3D/blob/development/Engine/source/platform/platformAssert.cpp#L176

https://github.com/GarageGames/Torque3D/blob/development/Engine/source/platformMac/macCarbStrings.cpp#L43

https://github.com/GarageGames/Torque3D/blob/development/Engine/source/platformWin32/winConsole.cpp#L137

https://github.com/GarageGames/Torque3D/blob/development/Engine/source/platformX86UNIX/x86UNIXConsole.cpp#L174

found using cppCheck against the engine/source/ folder.

**Comment by LuisAntonRebollo** [comment]
Thx for the report :)

**Comment by JeffProgrammer** [comment]
o_O probably not a good sign. surprised xcode or VS never complained about it.
