### ISSUE TITLE
OpenGL VBO Crash

### ISSUE THREAD

**Issue by JeffProgrammer** [GarageGames/Torque3D#1154]
Randomly during GUI rendering, a fatal assert is thrown saying that inside of GFXDrawUtil::drawBitmapStretchSR(), "Cannot access verts from an unlocked vertex buffer!!!" Yet, the vertex buffer handle has called .lock() before setting the points. verts[0].points.set() will throw a EXE_BAD_ACCESS

Has anybody seen this on windows or linux OpenGL during testing?

Will have to do some investigation...
- Using the OpenGL 3.2 CORE profile
- Mac OS 10.10.2 "yosemite"
- Intel Iris Pro OpenGL Engine OpenGL V 4.1
- 1536MB video ram

Although the branch is very similar, the only modifications on here is to get it to compile and run on OSX basic lighting.
https://github.com/JeffProgrammer/Torque3D/tree/mac-gl32-merge-dev

Crash is here: https://github.com/JeffProgrammer/Torque3D/blob/mac-gl32-merge-dev/Engine/source/gfx/gfxDrawUtil.cpp#L385

**Comment by JeffProgrammer** [comment]
Not a proper solution, but this seemed to make it stop throwing the error.

I need to do more testing though, but I think something could be up with glMap* on intel graphics osx...(dunno about other venders).

https://github.com/JeffProgrammer/Torque3D/commit/034371cc0fe1b6200f80e24f36389fab711b40a2

**Comment by JeffProgrammer** [comment]
If anybody else out there runs OSX, can you try running my branch and uncommenting my fix to see if it will crash while using the glMap* commands? I'm wondering if it's just 10.10.2's openGL driver, or my gpu, or something and not all macs...

**Comment by jamesu** [comment]
I can confirm this has also been reported to us by users on 10.10. I suspect something very odd is going on in the OSX Intel driver.

Should be noted other engines seem to have a fallback for when glMapBuffer & co return NULL. I imagine the correct solution in this case is to either pretend to lock the buffer OR wait for the driver to be "ready".

Would be interesting to see if the problem is in any way related to virtual memory allocations.

**Comment by JeffProgrammer** [comment]
@jamesu  has anybody reported this on an nvidia or ati card on OSX?

**Comment by jamesu** [comment]
No reports on nvidia or ati.

**Comment by JeffProgrammer** [comment]
@LuisAntonRebollo @jamesu maybe solution should be to set a capability on openGL for Intel drivers using yosemite versions between 10.10.0-10.10.x until it gets resolved? That has been done from the past from what I can tell. ?

**Comment by galek** [comment]
so maybe because yosemite is support only >=3.3 Core

**Comment by JeffProgrammer** [comment]
erm no...

Yosemite has support for 1.0-2.1 in a compatibility profile, and has a 3.2,-4.1 CORE profile implementation (same as Mavericks). It would have to be a bug in the mac intel driver as this is not happening to nvidia mac cards or amd mac cards using yosemite.

**Comment by JeffProgrammer** [comment]
@jamesu i read on a powerpoint from epic from GDC 2014 that they use malloc() and glBufferSubData() instead of glMap* as they found it to be performance hit. Unless i read that wrong, I can try to dig up the link if you are interested.

**Comment by jamesu** [comment]
@JeffProgrammer in the cortexgl branch we use an abstracted storage class which handles various buffer implementations, including a fallback to glBuffer calls.

It's frustrating how buggy something as simple as buffering in OpenGL can be. A lot of drivers seem to internally use malloc with a bad memory allocator when storing buffer data using certain calls which I suspect is causing a lot of problems with frequently updating buffers.

**Comment by JeffProgrammer** [comment]
Yeah, actually, it is "sort of" abstracted on what Luis has.....it has a choice of 3 options for volitile circular buffer. ARB_buffer_storage, glMap*, and fallback for what everything in theory should support. I agree with you, it's really annoying.

**Comment by JeffProgrammer** [comment]
I kinda wish opengl had another way in core to submit vertex data instead of using a buffer for volatile things. packing a buffer on the cpu and then sending it off every single frame seems rather waseful. Is it possible to use a standard old fixed function vertex array call with shaders in GL 2.1?

**Comment by jamesu** [comment]
@JeffProgrammer well there is arb_buffer_storage in gl 3. 

For those of us stuck with using mapBufferRange, it would be interesting to see if deferring glMapBufferRange volatile buffer updates so they occur before rendering calls in one huge chunk of a consistent size would be any improvement here. That would probably require a fair bit of architecting the gui drawing / particle drawing / skinning code though.

**Comment by JeffProgrammer** [comment]
ARB_buffer_storage is really a openGL 4.4 feature though, so I'm not sure if GL 3 cards really support it as an extension (and try asking apple for an extension on core ha!) (apple doesn't even support arb/ext on my system for buffer storage :( ). was there an older extension of ext_buffer_storage? Or am i confusing this call with another 4.4 feature :/

Hmm, yeah, i see what you mean. ugh...great...more re-engineering. :)

**Comment by jamesu** [comment]
@JeffProgrammer ati and nvidia have pinned memory extensions regardless. Intel on the other hand...

**Comment by JeffProgrammer** [comment]
@jamesu ah okay. but yeah, intel well.... :)

**Comment by galek** [comment]
@JeffProgrammer 
Yes,you right. I'm not correctly read notes Fabien Sanglard

**Comment by LuisAntonRebollo** [comment]
@JeffProgrammer, disable GL ARB_buffer_storage in GLEW fix the problem?
```cpp
__GLEW_ARB_buffer_storage = false;
```

**Comment by JeffProgrammer** [comment]
@LuisAntonRebollo  mac don't even support arb_buffer_storage, so the code just skips it since you have runtime checks. It's the glmapping
