### ISSUE TITLE
Revise OpengL texture format GFXFormatB8G8R8A8

### ISSUE THREAD

**Issue by LuisAntonRebollo** [GarageGames/Torque3D#1163]
> @Azaezel 
> need to review how opengl handles dds B8G8R8A8s. (seems to swizzle the channels)

@Azaezel  you have some problem with this format?

**Comment by LuisAntonRebollo** [comment]
@Azaezel helpme to confirm the problems using uncompressed dds BGRA texture.

**Comment by JeffProgrammer** [comment]
so what's the actual issue going on?

**Comment by Azaezel** [comment]
The core problem is that dx and opengl read bgra8's in completely swapped order. sent luis a sample.

**Comment by andr3wmac** [comment]
Could you explain a bit more? I mean GFXFormatB8G8R8A8 is defined differently between OpenGL and DirectX, so is this issue surprising? Or is the issue that the difference exists at all?

You have GFXFormatB8G8R8A8 creating D3DFMT_A8R8G8B8 (ARGB8) in DirectX:
https://github.com/GarageGames/Torque3D/blob/9c66aa06811f71f96a551cf035bb577671b0fc40/Engine/source/gfx/D3D9/pc/gfxD3D9EnumTranslate.pc.cpp#L90

In OpenGL you have one definition here for RGBA8:
https://github.com/GarageGames/Torque3D/blob/98e3651db55764dbffb66781f436b18faad4023c/Engine/source/gfx/gl/gfxGLEnumTranslate.cpp#L139

And another one here for BGRA8:
https://github.com/GarageGames/Torque3D/blob/98e3651db55764dbffb66781f436b18faad4023c/Engine/source/gfx/gl/gfxGLEnumTranslate.cpp#L160

So, there's inconsistency across the board. Is this the issue? Or is the issue you're reporting a result of this inconsistency? I don't know why this issue would be isolated to a single format such as DDS. Need more information please.
