### ISSUE TITLE
Gestalt no longer works on Mac OSX Yosemite

### ISSUE THREAD

**Issue by JeffProgrammer** [GarageGames/Torque3D#1166]
The Gestalt() function was deprecated since Mac OSX Mountain Lion. It no longer works properly on Yosemite, as the operating system returns mavericks while running Yosemite. A replacement will have to be made for newer versions of OSX.

(Not surprising it stopped working, it was a really old Carbon API function...)

I know It's kinda early to start reporting OSX bugs, but I am doing some work on OSX after all... ;)

**Comment by JeffProgrammer** [comment]
I got this. /me self assigns.

**Comment by eightyeight** [comment]
Thanks for the report and fix!
