### ISSUE TITLE
switch lighting the river disappears?

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1168]
I'm new to torque3d so sorry if I did a mistake, if this is normal and maybe I need to play more with the lights.

I use a laptop, the spec is very low. Therefore I always have basic lighting, sometimes I change to advance lighting and I realized this.

Basic
![river1](https://cloud.githubusercontent.com/assets/1057449/6096731/688e0516-af67-11e4-8c49-555bd7d5e844.png)

Advance (see the shadows in the background)
![river2](https://cloud.githubusercontent.com/assets/1057449/6096787/81a9d398-af69-11e4-85f1-4899e1787d4e.png)

Advance - Closer look
![river3](https://cloud.githubusercontent.com/assets/1057449/6096733/7bec41d6-af67-11e4-93ed-962f69c771a1.png)

![river4](https://cloud.githubusercontent.com/assets/1057449/6096779/536decd0-af69-11e4-9176-956cdb2118d5.png)

![river5](https://cloud.githubusercontent.com/assets/1057449/6096773/19799402-af69-11e4-8608-89e1126cd7c0.png)

**Comment by eightyeight** [comment]
Strange! Could you open `console.log` next to the game executable and paste its contents on [pastebin[(http://pastebin.com) or somewhere else we can look at it?

**Comment by John3** [comment]
Hi, Here:
http://pastebin.com/CVfQ96Ej

**Comment by eightyeight** [comment]
Ooh, looks like some shaders failed compilation. Not sure if that's expected. Will send someone here who knows what they're talking about :P.

**Comment by JeffProgrammer** [comment]
Must be a intel HD Graphics driver bug maybe? I've not seen this in the newer Intel Graphics.

**Comment by eightyeight** [comment]
Looks like advanced lighting isn't supported on your hardware, though there should really be a nice warning about that :/.

**Comment by Azaezel** [comment]
from the log:
C:/Torque3D/My Projects/TestSavanna/game/shaders/common/water/waterP.hlsl(158,23): error X3004: undeclared identifier 'prepassUncondition'

do you have a: 
game\shaders\procedural\autogenConditioners.h fie, or is that failing to be generated for some reason?

**Comment by John3** [comment]
ok... expected. Maybe we need to have on the wiki this technical stuff, graphics not supported.

Intel HD 2500, is the last graphics driver I think.

Driver Version: 15.33.32.64.4061
Intel(R) Graphics Driver: 10.18.10.4061

@Azaezel Yes I have the file, but for some reason is empty.

**Comment by Azaezel** [comment]
as far as it goes, and again, from the log file: 
Device created, setting adapter and enumerating modes
   Cur. D3DDevice ref count=1
   Pix version detected: 3.000000
   Vert version detected: 3.000000

advanced lighting caps out at 3.0, so I highly doubt it's that necessarily. 
reason I asked about the autogenConditioners.h file was thats where it'll be spitting out those prepassUncondition entries: http://pastebin.com/de0HQK13 as an example form this end.

**Comment by John3** [comment]
Ok the problem is my level. I don't why, but the file is empty always. For me it was weird because I used the Advanced Light at some point but I do not remember how it looked.

I tested the outpost level and everything seems good, and the file autogen is populated.

This level was copied from 3.6.2 to the folder 3.6.3 and then I regenerated with PM 2.2b. Have something to do?...
