### ISSUE TITLE
pool->flushWorkItems(); may not work as expected

### ISSUE THREAD

**Issue by lukaspj** [GarageGames/Torque3D#1174]
I was doing some multithreading on the particlesystem, the code can be found [here](https://gist.github.com/lukaspj/448c8910951ad6f4c232#file-particlethreading-cpp-L3-L11).

But I encountered an issue when there were several threads running, adding some debug info, I got this in the console:
```
Created queue
Finished a Particle Worker Thread
Finished a Particle Worker Thread
Finished a Particle Worker Thread
Finished a Particle Worker Thread
Deleting queue
Deleted queue
Created queue
Finished a Particle Worker Thread
Finished a Particle Worker Thread
Finished a Particle Worker Thread
Deleting queue
First-chance exception at 0x10E818EC (Empty_DEBUG DLL.dll) in Empty_DEBUG.exe: 0xC0000005: Access violation reading location 0xFEEEFEF6.
Deleted queue
```

As you can see, in the last pass, it deletes the queue before all the threads have finished, afaik `pool->flushWorkItems();` should ensure that all the threads have finished.

This is the main code that triggers this issue:
```c++
   OutputDebugStringA("Created queue\n");
   ParticleQueue* queue = new ParticleQueue(mParticlePool->GetParticleHead()->next);
   ThreadPool* pool = &ThreadPool::GLOBAL();

   F32 t = F32(ms) / 1000.0;

   for (U32 i = 0; i < 4; ++i)
   {
      ThreadSafeRef< ParticleUpdateItem > item(new ParticleUpdateItem(queue, t, this, BHVs));
      pool->queueWorkItem(item);
   }

   pool->flushWorkItems();

   OutputDebugStringA("Deleting queue\n");
   delete queue;
   OutputDebugStringA("Deleted queue\n");
```

**Comment by LuisAntonRebollo** [comment]
If i remember correctly ```flushWorkItems``` wait until all jobs are outside workItem queue.... but dont know about working/finished.

You can use ```ThreadSafeRef<ParticleQueue>``` stored on each ```ParticleUpdateItem```.

**Comment by lukaspj** [comment]
Ah I thought that outside workItem queue meant that they had been finished, but I guess it just means that they have been taken care of -or- "initiated"

**Comment by lukaspj** [comment]
Yeah that was simply it, sorry for bothering you, but this whole thing is not exactly perfectly described :)

**Comment by eightyeight** [comment]
Does that mean we need to [change the tests](https://github.com/GarageGames/Torque3D/blob/development/Engine/source/platform/threads/test/threadPoolTest.cpp#L66-L67)? I can't remember how directly I translated this test, but it suggests that work items *should* be complete after you call flush.

**Comment by lukaspj** [comment]
Oh yeah forgot about that, yes the tests need to be changed :P

I changed my code to this:
```c++
   ThreadSafeRef< ParticleUpdateItem > threads[4];
   for (U32 i = 0; i < 4; ++i)
   {
      threads[i] = ThreadSafeRef< ParticleUpdateItem >(new ParticleUpdateItem(queue, t, this, BHVs));
      pool->queueWorkItem(threads[i]);
   }

   pool->flushWorkItems();

   bool cont = false;
   while (!cont)
   {
      cont = true;
      for (U32 i = 0; i < 4; ++i)
      {
         if (!threads[i]->isDone())
            cont = false;
      }
      if (cont)
         break;
      Platform::sleep(25);
   }
```

Which works just fine for me.

**Comment by eightyeight** [comment]
There should probably be a method to wait for all threads in this way. Gonna give that a go.
