### ISSUE TITLE
Crash 3.6.3 GUI Editor Locks Up

### ISSUE THREAD

**Issue by SteveYorkshire** [GarageGames/Torque3D#1181]
Keep getting a crash/lockup in the new 3.6.3. Stock code, built with Project Manager 2.2 beta (+ missing xml file)
Open GUI editor up and then close twice and it all crashes.
Note: not an issue in 3.6.2.

To reproduce method 1:
Start a level, start GUI editor (F10), close it, reopen GUI editor (F10), close it again and crash/lock.
The error which loops into eternity.
To reproduce method 2:
At MainMenu open GUI Editor, close it, open it again and close aghain and crash/lock.
To reproduce method 3:
Open GUI Editor once, then exit and quit Torque. Lots of errors but T3D will quit before it locks.

The error which loops to crash:

>tools/guiEditor/scripts/guiEditorCanvas.ed.cs (223): Unknown command delete.
>  Object (4479) MenuBuilder

The script: tools/guiEditor/scripts/guiEditorCanvas.ed.cs
>
/// Called before onSleep when the canvas content is changed
function GuiEditCanvas::onDestroyMenu(%this)
{
   if( !isObject( %this.menuBar ) )
      return;
 >
   // Destroy menus     
   while( %this.menuBar.getCount() != 0 )
      %this.menuBar.getObject( 0 ).delete();//yorks - here be dragons!
>    
   %this.menuBar.removeFromCanvas();
   %this.menuBar.delete();
}

Thread I opened on the forums:
http://forums.torque3d.org/viewtopic.php?f=2&t=29

**Comment by eightyeight** [comment]
Missing XML file? You mean [this one](https://github.com/GarageGames/Torque3D/blob/development/projects.xml)? Also, this issue may be a duplicate of #1114.

**Comment by SteveYorkshire** [comment]
Yes that does look like the same issue.  Still, the superClass shouldn't be getting added to the set.
And yes, that xml file is/was not in the 2.2 beta zip.

**Comment by eightyeight** [comment]
It's not in the PM zip because it's included in the engine repo.

**Comment by eightyeight** [comment]
@SteveYorkshire are you able to reproduce this with the latest development branch? I can't, with any of those 3 approaches!

**Comment by SteveYorkshire** [comment]
It's an issue in 3.6.3, I don't use the devhead because I can never remember how github works ;)

**Comment by SteveYorkshire** [comment]
Az reminded me that I can actually download the dev branch, so after testing, I am no longer seeing the issue in development. Looks like just 3.6.3 master. Closing this issue.

**Comment by eightyeight** [comment]
Cool. Slightly worrying, but I won't look a gift horse in the mouth.
