### ISSUE TITLE
#define TORQUE_RELEASE doesnt get defined for release builds

### ISSUE THREAD

**Issue by adambeer** [GarageGames/Torque3D#1191]
When browsing through the torqueConfig.h, I noticed that TORQUE_RELEASE wasn't defined when it was a release build but TORQUE_DEBUG would define properly.

**Comment by eightyeight** [comment]
I'm pretty sure `TORQUE_RELEASE` is intended to be enabled manually when you actually make a release, not just when you make a release build, maybe? Or possibly I'm thinking of `TORQUE_SHIPPING`.

**Comment by adambeer** [comment]
Yea the manual one is TORQUE_SHIPPING.
