### ISSUE TITLE
HDR Resize Bug

### ISSUE THREAD

**Issue by galek** [GarageGames/Torque3D#1193]
Render: OpenGL
Hardware: i7 4790K,GTX970

1. Start Engine in window
2. Run Editor
3. Do resize(using in windows 7 style-move window pressed mouse on header)
4. See HDR bug

**Comment by eightyeight** [comment]
Thanks for the report!

**Comment by lukaspj** [comment]
Hey guys, just testing something out.

[Here](https://freedomsponsors.org/issue/637/hdr-resize-bug?alert=SPONSOR#) you can find a small bounty on this issue. If you fix it you can collect it :P

**Comment by eightyeight** [comment]
But first you have to find a way to reproduce it ;P.

**Comment by lukaspj** [comment]
Didn't test it but seems like it's a 4-step process to repro. Make sure to notice that it is in OpenGL :P

**Comment by LuisAntonRebollo** [comment]
@galek , can you post a comparision screenshot? For have a better idea about the problem.

**Comment by lukaspj** [comment]
I think @Azaezel reproduced it too.

**Comment by Azaezel** [comment]
yes and no. Managed to sporadically get white flickers that seemed to change as the sun went down while the console was open on outpost by resizing it. Couldn't consistently reproduce it however, nor reduce it down to hdr being on or off.

**Comment by galek** [comment]
On Thursday I will do this until there is no time.
For Note:Render was modificated for support Deferred Shading from some fork(forgot name)

**Comment by Azaezel** [comment]
ok, 2 things. 
A) That hasn't been rolled in yet, so you want to fill a ticket either https://github.com/andr3wmac/Torque3D/issues or https://github.com/Azaezel/Torque3D/issues depending on which one you grabed.
B) Tried the same reproduction outlined here a couple of times, and again, came up with no result. Whichever version you've got, could you include a log and a sceeenshot to clarify the bug?

**Comment by lukaspj** [comment]
Ok so if this isn't an actual stock issue, then I'll be revoking the bounty :P

**Comment by eightyeight** [comment]
Please open a new issue at the relevant repository, linking to this one if you need to :).
