### ISSUE TITLE
unit tests for matrixf_X_matrixF causing non-compilation.

### ISSUE THREAD

**Issue by Azaezel** [GarageGames/Torque3D#1197]
Error   146     error LNK2019: unresolved external symbol _SSE_MatrixF_x_MatrixF referenced in function "private: virtual void __thiscall MatrixF_MultiplyImplmentations_Test::TestBody(void)" (?TestBody@MatrixF_MultiplyImplmentations_Test@@EAEXXZ)
Error   314     error LNK2019: unresolved external symbol _SSE_MatrixF_x_MatrixF referenced in function "private: virtual void __thiscall MatrixF_MultiplyImplmentations_Test::TestBody(void)" (?TestBody@MatrixF_MultiplyImplmentations_Test@@EAEXXZ)

file tag:
https://github.com/GarageGames/Torque3D/blob/47626684ce3d6c65bbccfcbf216b6013b8a9b059/Engine/source/math/test/mMatrixTest.cpp#L34

**Comment by eightyeight** [comment]
Compiler and windows version? CMake or PG? I have no idea what the appropriate define guards for this should be - this was copied verbatim from old code. Though it didn't seem to break when it was in the engine before porting to googletest.

One option is to simply nuke this test. Pretty sure matrix mult is working okay, or the engine would be pretty much broken :P.

**Comment by Azaezel** [comment]
VS2013, win8,1 and cmake, respectively. I belive @dottools had a few observations on the matter reguarding the AMD math assembly, but I was darting out the door at the time, and didn't catch if there were any tested resolutions to the matter at the time.

**Comment by LuisAntonRebollo** [comment]
I think remove ```extern "C"``` can work -> https://github.com/GarageGames/Torque3D/blob/47626684ce3d6c65bbccfcbf216b6013b8a9b059/Engine/source/math/test/mMatrixTest.cpp#L34

**Comment by Azaezel** [comment]
4	IntelliSense: identifier "SSE_MatrixF_x_MatrixF" is undefined
	3	IntelliSense: identifier "Athlon_MatrixF_x_MatrixF" is undefined
Error	2	error C3861: 'SSE_MatrixF_x_MatrixF': identifier not found
Error	1	error C3861: 'Athlon_MatrixF_x_MatrixF': identifier not found

**Comment by LuisAntonRebollo** [comment]
Fixed on #1202
