### ISSUE TITLE
Replace GFX with BGFX

### ISSUE THREAD

**Issue by lukaspj** [GarageGames/Torque3D#1207]
I believe Torque3D could benefit greatly from offloading the GFX system to the [BGFX library](https://github.com/bkaradzic/bgfx).

License is [BSD 2](https://github.com/bkaradzic/bgfx/blob/master/LICENSE) which AFAIK is compatible with MIT.

Not only would this open up a whole new set of features, it'd also mean that we don't have to worry as much about the graphics layer. It's multiplatform, comes with a cross-api shading language and a big cross-application community.

@andr3wmac had a bgfx branch [here](https://github.com/andr3wmac/Torque3D/tree/bgfx) not sure how far it is, probably not that far.

**Comment by lukaspj** [comment]
I placed a 50$ bounty on this issue: https://freedomsponsors.org/issue/643/replace-gfx-with-bgfx

**Comment by eightyeight** [comment]
I don't think this is really a Github sort of issue since it isn't immediately actionable or unanimously decided upon.

**Comment by lukaspj** [comment]
Ah sure, I just saw the OpenGL/Linux ones and thought this might fit in too.
