### ISSUE TITLE
Implement Static Global Illumination

### ISSUE THREAD

**Issue by lukaspj** [GarageGames/Torque3D#1208]
As describe [here](http://forums.torque3d.org/viewtopic.php?f=9&t=5).

**Comment by Areloch** [comment]
The GI implement I've been eyeballing is SVOTI - Sparse Voxel Octree Total Illumination, which is used by Crytek, which is the non-static, big brother version of the old OfflineLPV experiments. So if we go with anything in the bracket, it'd be that. I'll go ahead and close this ticket for now
