### ISSUE TITLE
Creating GFX Null Device when running Linux (radeon driver)

### ISSUE THREAD

**Issue by pbrand** [GarageGames/Torque3D#1233]
When running the Torque3D engine (not the dedicated server) under Fedora, which uses the open source radeon drivers (2x HD6850 in crossfire setup), results in the following error:

```
The requested renderer, D3D9, doesn't seem to be available. Trying the default, OpenGL. 
The OpenGL renderer doesn't seem to be available. Trying the GFXNulDevice. 
Attempting to create GFX device: GFX Null Device [] 
Initializing GFXCardProfiler (GFX Null Device Renderer)
  o Chipset : 'NULL Device' 
  o Card : 'GFX Null Device Card'
  o Version : '0'
  o VRAM : 0 MB  

Scanning card capabilities...
Loading card profiles...
No card profile core/profile/GFXNullDeviceRenderer.cs exists
No card profile core/profile/GFXNullDeviceRenderer.NULLDevice.cs exists
No card profile core/profile/GFXNullDeviceRenderer.NULLDevice.GFXNullDeviceCard.cs exists
No card profile core/profile/GFXNullDeviceRenderer.NULLDevice.GFXNullDeviceCard.0.cs exists
Device created, setting adapter and enumerating modes 
% Segmentation fault (core dumped)
```

**Comment by JeffProgrammer** [comment]
I wonder if it would work with mesa drivers?

**Comment by eightyeight** [comment]
Do I need to triple-boot and see if I can get Fedora working natively on my R9? :P

**Comment by JeffProgrammer** [comment]
yes :D

**Comment by pbrand** [comment]
No worries, I'll save you the hassle of dropping back to the open source radeon driver. Your R9 will probably cry you a river if you'd do that :p so I'll look into it. 

I do use mesa drivers in combination with radeon. glxgears and glxinfo show that OpenGL should work fine in this setup I suppose and this problem is confirmed for Ubuntu 14.04 as well.

**Comment by JeffProgrammer** [comment]
@pbrand how is mesa driver performance with amd cards on linux? I was curious, as I don't have any amd cards (I'm an nvidia fanboy :l)

**Comment by pbrand** [comment]
I haven't checked the performance of the mesa driver actually, but if you are interested I'm willing to run some tests. Do you have any suggestions for measuring the performance or a specific benchmark for instance?
Unfortunately I won't be able to test it against the proprietary fglrx driver, as some wayland support is enabled since fedora 20 which isn't supported by any proprietary graphics card driver at this moment (as far as I know).

**Comment by JeffProgrammer** [comment]
i'd like to know the milliseconds per frame inside of the "outpost" level. Once in game, go into the console and type metrics("fps");

**Comment by pbrand** [comment]
Sorry for the late reply, I've been a bit busy lately. Anyway, if I'm able to fix this issue I will check it and post the results here :)

**Comment by Calinou** [comment]
I have had the same issue using the Nouveau driver.

**Comment by pbrand** [comment]
Thanks for the log :)
It is true that Wayland is not enabled by default, but as far as I know the support of Wayland was enabled in some packages which made the system crash when using the proprietary AMD drivers. I remember reading something about people recompiling the packages without Wayland support before getting fglrx to work. But to be honest, he last time that I checked was about a year ago so things might have improved by now.

**Comment by hpvb** [comment]
Could you please test https://github.com/GarageGames/Torque3D/pull/1348 and see if this solves the issue on nouveau for you as well? The PR isn't ready for merging yet but it should fix this issue.
