### ISSUE TITLE
Image muzzle flash animations play constantly

### ISSUE THREAD

**Issue by eightyeight** [GarageGames/Torque3D#1235]
Error introduced by #1054. Muzzle flares constantly visible. See image.

![bug](https://cloud.githubusercontent.com/assets/904269/6439672/16c21082-c129-11e4-8ece-003c0449b293.png)

**Comment by Azaezel** [comment]
fixed by https://github.com/GarageGames/Torque3D/commit/74a05854d56afe15cbc341575b73b3474af18277
