### ISSUE TITLE
CMake error: prevented in-tree built (SDL)

### ISSUE THREAD

**Issue by Calinou** [GarageGames/Torque3D#1247]
Operating system is Ubuntu 14.10 64-bit. Latest clone of Torque 3D from today. I tried using `cmake .` and `mkdir build; cd build; cmake ..`, both return the same error.

```
CMake Error at Engine/lib/sdl/CMakeLists.txt:2 (message):
  Prevented in-tree built.  Please create a build directory outside of the
  SDL source code and call cmake from there


-- Configuring incomplete, errors occurred!
```

**Comment by eightyeight** [comment]
Interesting. In Ubuntu 14.04 I can reproduce the error using `cmake . -DTORQUE_APP_NAME=test`, but not if I make a `build` folder. CMake version 2.8.12.2...

**Comment by Calinou** [comment]
I only have `My Projects` with a a `readme.txt` inside…

**Comment by eightyeight** [comment]
Ah right. To create a new project, follow [these instructions](http://wiki.torque3d.org/introduction:creating-a-project-without-the-project-manager). We really need to add an end-to-end make-a-game tutorial. Most of us are just very used to the project layout at this point :joy:

**Comment by Calinou** [comment]
I don't see CMake files inside the Empty and Full templates.

**Comment by Calinou** [comment]
It works.

**Comment by eightyeight** [comment]
Oh, so did command-line CMake still give the same error? Could you post the entire command-line call? Usually it's also required to add `-DTORQUE_APP_NAME` at least, so the command-line snippets you posted above should have failed because of that.

And yeah, the warning count is a known issue :P.

**Comment by Calinou** [comment]
Nevermind, it works in command-line too.

**Comment by LuisAntonRebollo** [comment]
Yep, sorry... bad docs was my fault :(

This weekend is only for improve all Linux/Opengl documentation,
