### ISSUE TITLE
fullscreen alt+tab erorrs

### ISSUE THREAD

**Issue by Azaezel** [GarageGames/Torque3D#1250]
alt+tab in fullscreen on windows (8, if it matters) in opengl mode does not properly reset to the prior desktop resolution

in directx mode, it does, however when alt+tabing back to game, the first time, preview shows mismatched window border and playgui, then when it actually gets back 'in-game', scrolling corrpution. a second attempt will crash the application.

attempting to debug the error via visual studio 2013 ends up getting 'caught' (can't tell if it's an ap-hang or not) unable to alt tab a second time to view any breaks.

**Comment by jamesu** [comment]
You should probably consider implementing borderless fullscreen support. Doesn't require mode setting and works nicer on multi-display setups. Plus in the case of linux it's 100x more reliable. ;)

**Comment by Azaezel** [comment]
intermediary isolation report: https://github.com/GarageGames/Torque3D/pull/1072 triggered it. (could take a bit to wade through)

**Comment by LuisAntonRebollo** [comment]
Confirmed, we have some problem with this :(

```
gfxTextureManager.cpp(142,0): {Fatal} - Texture Manager already a zombie!
```

**Comment by LuisAntonRebollo** [comment]
@Azaezel , can you test if problem is fixed?

**Comment by Azaezel** [comment]
verrified

**Comment by LuisAntonRebollo** [comment]
Thx for test :)
