### ISSUE TITLE
Menu Bar hidden (Development Branch) 

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1254]
Testing Development Branch (Compiled with VS2010)

Project Manager 2.2 (Binary)
Generated with:
- Bullet
- OpenGL Rendering
- Full Template

I don't know if is  know bug, today synced with the repo.

When you enter to world editor you can see the menu, if you go to GuiEditor and then come back, the menu bar disappear. You need to enter the game (F11) and then come back again.

![1](https://cloud.githubusercontent.com/assets/1057449/6653430/7434bec6-ca58-11e4-9c90-d43d53ce4892.JPG)

**Comment by eightyeight** [comment]
Oh wow... will try to verify.

**Comment by John3** [comment]
Hi,
I was reviewing my reported issues :D and this happen by this commit: https://github.com/GarageGames/Torque3D/commit/de82fbe0f900af5e18684ee1b642a785518c58e3
@Areloch 
@Lopuska

**Comment by Areloch** [comment]
Should be corrected with #1933
