### ISSUE TITLE
Material Preview empty (Development Branch)

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1256]
Testing Development Branch (Compiled with VS2010)
Project Manager 2.2 (Binary)
Generated with:
- Bullet
- OpenGL Rendering

![materialpreview](https://cloud.githubusercontent.com/assets/1057449/6654350/5f5bdde2-ca83-11e4-8503-e8968ae42cad.JPG)

**Comment by eightyeight** [comment]
Mmm, look at that delicious shading acne.

**Comment by John3** [comment]
Updated. Branch: release-3.7

Has a flickering on the dark side.

![materialpreview](https://cloud.githubusercontent.com/assets/1057449/7379558/4d3d1486-edbb-11e4-8096-6eb3ec3cc29d.JPG)

![materialpreview2](https://cloud.githubusercontent.com/assets/1057449/7379623/c754d1f0-edbb-11e4-9f3c-aa33b11c9fdc.JPG)

**Comment by eightyeight** [comment]
This is an OpenGL issue, so I'm going to make an executive decision and defer this to 3.8 in the interests of getting 3.7 out quicker, especially since a significant portion of our OpenGL effort (i.e. Luis) is out of action for a little while.

**Comment by John3** [comment]
Maybe is a minor bug and we can have it closed, anyway still exist for D3D9 and OpenGL, and the bug is present under certain condition, not sure why.

Default CMake options, win32 and x64 build, OpenGL and D3D11, Template Full, VS2015

**video bug:** https://drive.google.com/file/d/0B9GUwtDHCp_eZWFGSzJmX2hzalE

**Comment by Areloch** [comment]
Very odd.

I was testing this and it's showing up just fine. I can't get it to replicate that at all. There's some occasional, minor flickering in the backdrop, but nothing that affects the preview shape itself on both win and lin.

Do you have the latest drivers?

**Comment by John3** [comment]
Yes I know I can't replicate :( 

When I opened the issue I was using an Intel Graphics with last driver, and now a nvidia with last driver v342. Anyway way nothing to worry about, I wanted to give a update to the issue. Thx Areloch.
