### ISSUE TITLE
Terrain Editor and River Editor Overlayed.

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1261]
I was building a river, smoothing some peacks and then come back and so on... with T3D development branch and then everything overlayed, the file console.log don't said anything.

![topbar](https://cloud.githubusercontent.com/assets/1057449/6767986/3ea948f8-d016-11e4-874a-746a018d7ad6.JPG)

Do not know how to reproduce it.
forum: http://forums.torque3d.org/viewtopic.php?f=12&t=138

**Comment by Areloch** [comment]
Unless we can replicate this, I'm gunna figure it was a fluke one-off and we'll not really worry about it.
