### ISSUE TITLE
WheeledVehicle not effected by Physical Zones

### ISSUE THREAD

**Issue by WaxyChicken** [GarageGames/Torque3D#1262]
Found in T3D MIT V3.6.1

Flying vehicles and players are effected by PhysicalZones.
Wheeled vehicles are not - not by velocity, gravity, or applied force.
HoverVehicles i don't know about.

Proven with these values:

Physical Zone Properties in Question:
velocityMod 1
GravityMod (tried 0 and -2)
AppliedForce ( 0 -20000 0)

WheeledVehicle properties in question:
Mass 600
Drag 0.6
Density 4

haven't tried with other values, but with -2 gravity and 20000 push force the vehicle should at least shake, no?

**Comment by Azaezel** [comment]
verified. appended

   new PhysicalZone() {
      velocityMod = "1";
      gravityMod = "0.5";
      appliedForce = "0 0 25000";
      polyhedron = "-0.5000000 0.5000000 0.0000000 1.0000000 0.0000000 0.0000000 0.0000000 -1.0000000 0.0000000 0.0000000 0.0000000 1.0000000";
      position = "29.7831 -40.6796 244.211";
      rotation = "1 0 0 0";
      scale = "5 5 50";
      canSave = "1";
      canSaveDynamicFields = "1";
   };
to outpost (right at the cheetah spawn) and drove over it a few times. no effect on the WheeledVehicle.

**Comment by Areloch** [comment]
Fixed in PR #1263
