### ISSUE TITLE
No OpenAL output in Debian Wheezy

### ISSUE THREAD

**Issue by Levitator1** [GarageGames/Torque3D#1265]
Reposted as requested:

It builds! It runs! However, there is no sound on Debian Wheezy. During startup, I see this in the console:

SFXSystem::createDevice - created OpenAL device 'OpenAL Soft'
Provider: OpenAL
Device: OpenAL Soft
Hardware: No
Buffers: 16

I hear a brief crackle as this scrolls by, but when playing the demo maps, there is no sound at all. It was just now suggested to me to try FMOD instead.

**Comment by JeffProgrammer** [comment]
afaik the FMOD implementation in torque is the old one, and requires the use of the legacy version of fmod, not the new one with the indie license :(

**Comment by eightyeight** [comment]
Just realised this was fixed.
