### ISSUE TITLE
Fixed Function Pipeline needs removing

### ISSUE THREAD

**Issue by jamesu** [GarageGames/Torque3D#1267]
When working on the oculus stuff with stock T3D development, I noticed a rather bizarre rendering bug. The problem was the first thing I rendered after the oculus display (which uses its own rendering code with the same D3D9 device) didn't get rendered, despite resetting the rendering state with:

```
GFX->disableShaders();
GFX->updateStates(true);
```

After 3 hours I discovered to my horror that in GFXD3D9Device::setupGenericShaders the fixed function pipeline is used for GUI rendering which meant the shaders never got disabled since the engine thought the shader was still 0x0.

It's 2015. Why on earth does stock T3D still have a fixed function rendering pipeline fallback?

**Comment by JeffProgrammer** [comment]
fixed function forever! long live FFP!

**Comment by LuisAntonRebollo** [comment]
:+1:  to remove FFP.

Remember me to kill @JeffProgrammer :P

**Comment by JeffProgrammer** [comment]
I joke I joke, remove that old thing :D
