### ISSUE TITLE
Linux FileDialog does not work in 3.7 current

### ISSUE THREAD

**Issue by Areloch** [GarageGames/Torque3D#1274]
FileDialog does not currently work for linux, as the execute function for the linux platform code just returns false. 

Needs to get an implementation so stuff can be saved through the editor.

**Comment by Areloch** [comment]
Whoops, forgot the linux tag.

Tim and Az found these as potential options to work alongside SDL to handle the window stuff:

http://forums.libsdl.org/viewtopic.php?p=46742&sid=160f4c96e8d3e06645bf874b40aa35ff

http://forums.libsdl.org/viewtopic.php?p=46006&sid=bdc8b322aa62cdb27c3221e6339c4b1f

**Comment by LuisAntonRebollo** [comment]
I like the idea :+1:
