### ISSUE TITLE
Level save with populated forest results in "FileStream::open::empty filename"

### ISSUE THREAD

**Issue by aurodev** [GarageGames/Torque3D#1277]
When saving a level following addition of trees with the forest brush the editor asserts with "FileStream::open::empty filename". 

Even when ensuring an existing forest data file is selected in the inspector and also when previously saving a level with an empty forest successfully.

v.3.6.3 from git

File:
game\tools\forestEditor\main.cs ->
function ForestEditorPlugin::onSaveMission( %this, %missionFile )
{
   ForestDataManager.saveDirty();

 
 if ( isObject( theForest ) )
theForest.saveDataFile();

  ForestBrushGroup.save( "art/forest/brushes.cs" );
}

Temp Workaround:
Hardcoding a path/filename: 
 if ( isObject( theForest ) )
theForest.saveDataFile("tempForestFile.forest");

**Comment by eightyeight** [comment]
Thanks for the report! Is this on the development branch?

**Comment by aurodev** [comment]
I think it was 3.6.3 development.

**Comment by eightyeight** [comment]
Okay, thanks!

**Comment by aurodev** [comment]
yw!
Just now built and tested 3.7 release with the same behavior.   
I need to get up to speed and get on the forums.

Perhaps grab the forest "dataFile" somehow from the .mis or %mission in main.cs...

Thanks for the hard work guys!

**Comment by John3** [comment]
HI, don't know if the same bug, I was playing around t3d 3.7rc with walkabout. Added some trees save the level and the next day I open my level and all trees was gone.

![forestbug](https://cloud.githubusercontent.com/assets/1057449/7301087/f3083f40-e9a5-11e4-8210-d47c0e5e8263.JPG)

**Comment by Areloch** [comment]
Fixed with the assocaited PR. Apparently formatted the comment incorrectly to have github automatically associate them. Closing manually.
