### ISSUE TITLE
Vignette PostFX does not save

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1302]
The Vignette PostFX does not save it's values to the postfx.preset file or anywhere else, only on or off gets saved, the strength slider will get reset on game reload.
At the same time the setting for vignette will get carried over to other levels when you open them, even if you did not enable vignette for them.

https://github.com/GarageGames/Torque3D/commit/0e346fed9ffd509b205ab9cba73e0fb34ca902ad

As far as I can see it uses a variable, but it does not get saved anywhere as a preference or so and it does not have variables that get saved in the postfx presets except the on/off button.
No idea how it is supposed to work, but to me it looks like it should be possible to define the vignette values into postfx presets for each mission.

**Comment by eightyeight** [comment]
Definitely. Will get on it.
