### ISSUE TITLE
Crash on Ubuntu when exiting from editor

### ISSUE THREAD

**Issue by crabmusket** [GarageGames/Torque3D#1311]
I open a mission as usual, open the editor with F11, then select 'File -> Exit Level'. I get a fatal assert here:

```
/media/daniel/DATA/code/Torque/linux/Engine/source/platformSDL/menus/menuBarSDL.cpp(115,0): {Fatal} - 
% Exiting
```

Ubuntu 14.04 x64, compiled with gcc/make.

**Comment by fr0zi** [comment]
The same crash can happen while switching through game <-> World Editor with F11 key for couple of times. (OpenSUSE 13.2 x64, gcc, make)

**Comment by mkrawiec** [comment]
Same on openSUSE Tumbleweed. Happens (almost) every time when switching from World Editor to the game.

**Comment by Azaezel** [comment]
https://github.com/GarageGames/Torque3D/pull/1114 have any impact y'alls end?

**Comment by eightyeight** [comment]
Erk, should test that out.

**Comment by hreikin** [comment]
I get this error when doing pretty much anything from switching editor to using any of the menus or trying to exit Torque3D, sometimes i can get 5 minutes before it happens sometimes its the first thing i click.

I tried changing the file as suggested in the issue @Azaezel linked but i still encounter the same error, i'm running Ubuntu 14.04 x64, compiled with gcc/make, here is a pastebin of my console.log : http://pastebin.com/LkMA0Lgp

**Comment by Areloch** [comment]
Seems to largely be resolved through various fixes.
