### ISSUE TITLE
Flickering with colors blue,red and green. Shape editor.

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1312]
t3d 3.7rc

1)
- Activate "Show Nodes"
- Activate "Wireframe"

Began an oddish flickering with colors blue,red and green. Sorry but can't take a pic, for some reason the screenshot don't show the bug.

2)
- Activate "Show Nodes"
- Activate "Shape transparency"
  ![shapeeditor1](https://cloud.githubusercontent.com/assets/1057449/7669077/ee18b668-fc24-11e4-8f75-35c14e05309b.JPG)

**Comment by eightyeight** [comment]
I can reproduce the second problem on Ubuntu 14.04 x64 with gcc/make, but not the first. And neither on Windows DX. Can't test Windows OpenGL :/. Second looks like the crosshatching transparency shader is acting up somehow.

**Comment by JeffProgrammer** [comment]
@John3 @eightyeight  does this happen on windows opengl implementation?

**Comment by eightyeight** [comment]
Haven't been able to test. Will do so ASAP.

**Comment by John3** [comment]
I can't reproduce the errors. I'm using 3.8-dev same compiled options, vs2010, opengl and bullet. I suppose the error is fixed, I think we can close the bug unless @eightyeight can reproduce the error... Thanks!
