### ISSUE TITLE
particle glow bug

### ISSUE THREAD

**Issue by Azaezel** [GarageGames/Torque3D#1315]
Directx shown: https://youtu.be/PZrZyB1PI5g uses https://github.com/GarageGames/Torque3D/pull/863 for debug viewing. Thoughts @lukaspj?

**Comment by lukaspj** [comment]
That is sooo odd...

**Comment by lukaspj** [comment]
If you've got the time, could you check that they are added here:
https://github.com/GarageGames/Torque3D/blob/30a8401d1461564a283810daacf78b5f6043a8d5/Engine/source/renderInstance/renderGlowMgr.cpp#L132-L136

And rendered here: https://github.com/GarageGames/Torque3D/blob/30a8401d1461564a283810daacf78b5f6043a8d5/Engine/source/renderInstance/renderGlowMgr.cpp#L184-L208
?

**Comment by Azaezel** [comment]
Both trigger in debug mode, yes.
