### ISSUE TITLE
OpenGl Terrain blend seams

### ISSUE THREAD

**Issue by aurodev** [GarageGames/Torque3D#1318]
Terrain texture seams at blend edges with 2+  texture layers, only in OpenGl.

Occurs when using any detail texture and seems independent of square size, resolutions, base texture size etc.

Only tested on AMD Radeon HD7700 + updated drivers.
Win 8.1
Tested with Torque v3.6.3 and  3.7 Release

Solution / workaround   
 In game\shaders\common\terrain\terrain.glsl
**uv += 0.00195;**
vec2 xy = floor( uv );

Forum post:http://forums.torque3d.org/viewtopic.php?f=9&t=231

![seam4](https://cloud.githubusercontent.com/assets/7356383/7888730/9f176602-0608-11e5-9762-6eca6d8d2f3f.png)
![seam2](https://cloud.githubusercontent.com/assets/7356383/7888738/adf5ef54-0608-11e5-8728-f72be232fc97.png)

![seam3](https://cloud.githubusercontent.com/assets/7356383/7888736/a7c37d5e-0608-11e5-8b44-66310f7460af.png)

**Comment by aurodev** [comment]
Someone noted that the terrain textures look like they have no detail textures
http://forums.torque3d.org/viewtopic.php?f=9&t=231&p=1893#p1893

Adding additional pics for clarity
**OpenGl**
![newseamsfourmpost2](https://cloud.githubusercontent.com/assets/7356383/7898012/a4a28d6e-06c0-11e5-8a35-a75293b4711e.png)

![newseamforumpost3](https://cloud.githubusercontent.com/assets/7356383/7898014/c392b654-06c0-11e5-9d4b-d9228ede1043.png)


![newseamsfourmpost4](https://cloud.githubusercontent.com/assets/7356383/7898020/f3202d20-06c0-11e5-9a8a-bc951d1d91fb.png)


![newseamsforumpost5](https://cloud.githubusercontent.com/assets/7356383/7898021/f73ddce0-06c0-11e5-993b-e0d3427d1334.png)

**Comment by lukaspj** [comment]
Seems like an off-by-one error in texcoords

**Comment by Areloch** [comment]
Have not been able to replicate this out of apparent rather specific hardware circumstances. I'm pushing this issue back to 3.9 so we can keep an eye on it, but unless we can get a more generally easier to replicate setup to better track it, options to fix and test are limited.
