### ISSUE TITLE
OpenGL only rendering the canvas clear color for 3.7 Release

### ISSUE THREAD

**Issue by aurodev** [GarageGames/Torque3D#1335]
Latest 3.7 releases from the wiki and github have broken OpenGL 
on AMD Radeon HD 7700 + Win 8.1

- **The 3.7 development branch pulled on 6.27.2015 works fine.**
- The 3.7 Master branch displays broken behavior on this system

Win 8.1
AMD Radeon HD 7700 
AMD FX(tm)-6350 Six-Core Processor, 3900 Mhz, 3 Core(s), 6 Logical Processor(s)
Direct3D Version	9.14.10.01080
OpenGL Version	6.14.10.13283

Console log: https://www.dropbox.com/s/12ualthdsyzmfjd/console.log?dl=0
Issue seems to start at:
*“OPENGL: glUniform3fv has failed because the operation requires a currently active program object (GL_INVALID_OPERATION)”*

- OpenGL only displays the canvas clear color in the editor
- Only working Debug Render is Bounding Boxes
- Tested with Empty Room, Empty Terrain and Outpost
- Behavior is the same for projects from the wiki files **Torque3D-3.7.zip**, **Torque3D-3.7-Win.zip** and  github **Torque3D-master.zip** pulled on 6.26 and 6.27
- The 3.7 development branch pulled on 6.27.2015 works fine.

OpenGL works well on this system with:
* Previous 3.7 dev and “release” pulled from Github on 5.29.15 
* Previous releases, e.g. 3.63, Azaezel's PBR branch etc. 

**Examples**
![torqueogl1](https://cloud.githubusercontent.com/assets/7356383/8393281/69e07dbc-1cd7-11e5-8bc4-2a4a48b7f98f.png)

![torqueogl2](https://cloud.githubusercontent.com/assets/7356383/8393283/74f39ec8-1cd7-11e5-92fd-a27406e9cbb2.png)

![torqueogl3](https://cloud.githubusercontent.com/assets/7356383/8393285/79416e2e-1cd7-11e5-94a7-8d7533725e0a.png)

**Comment by eightyeight** [comment]
To confirm, is it really the case that the development branch is completely fixed? If so, then this will become a documentation issue. We won't go back and modify the 3.7 release, and I don't fancy doing a 3.7.1 release, but rather pushing to get 3.8 out quicker. If the issue is gone in development, I'll add something to the documentation. I'm thinking a prominent OpenGL overview page on the wiki with compatibility notes and so on.

**Comment by Azaezel** [comment]
Verified with a clean build from master. I can say that this was the precise behavior exhibited by the alterations introduced 
https://github.com/GarageGames/Torque3D/commit/3a457749ec7dba8ae8f2d3220ee3a125997824df#diff-ccc46cf2cb396a19576616c0b31558a0L698
and corrected by https://github.com/GarageGames/Torque3D/commit/b5f8e9aa707d9b61604868532b1059ef80bbd007 though to be clear, looking through the master codebase, the former has not been included, so it's a similar point of failure. not the cause.

**Comment by Azaezel** [comment]
Second verification that development head at time of writing, which includes 3.7 does not exhibit this behavior. So something got left out, looks like.

**Comment by eightyeight** [comment]
Hmm, okay.

**Comment by aurodev** [comment]
sorry was afk 
"Do you mean the 3.7 pre release? Or just a source bundle?"
Probably 3.7 pre release, have been playing with so many including pbr, old fbx fork etc.  

So just play with the dev branch til 3.8, got it!  :+1:
