### ISSUE TITLE
Bullet BtWorld crash

### ISSUE THREAD

**Issue by dragutux** [GarageGames/Torque3D#1337]
Happening when loading outpost, bullet physics.

i suspect the polysoup after Azaezel contributed to investigate the issue further down 
with me, we were able to load outpost mission after deleting the mesh road.

prior to that, several items were removed to no effect. another crash happened when
i was visiting the static buildings.

i do suspect some part of the code is getting NaN numbers at the convex sweeps passes
i do not know how to label this, but its a Bug / crash that need fixing, it is happening only
in debug mode if that can help, something is deactivated in release that does not trigger
this crash.

**Comment by dragutux** [comment]
further notes : not happening in t3d base physics, as for now untested on physx 3.

**Comment by Azaezel** [comment]
https://www.youtube.com/watch?v=3OK7eEZa4Cw couple quick alts to suppress the crashes. not thoroughly tested, and there is that side-effect to crosscheck vs the normal behavior of the walkableshape flag for statics.

**Comment by dragutux** [comment]
the colision mesh works again with this but is not as accurate as visible mesh (convex bullet hulls) also, we can avoid the crash with that patch but its an absolute if not negative filter, this should check that if a wall is found, its not climbable.

how to do so ? well, is that number an angle check for the slopes ?

**Comment by dragutux** [comment]
we can consider it closed (see eightyeight commit)
