### ISSUE TITLE
Arch Linux segfault during GuiCanvas creation

### ISSUE THREAD

**Issue by eightyeight** [GarageGames/Torque3D#1345]
See gdb log [here](https://gist.github.com/anonymous/06543aa1da344ab43fd7). Fault appears to happen [here](https://github.com/GarageGames/Torque3D/blob/development/Engine/source/gui/core/guiCanvas.cpp#L266).

**Comment by hpvb** [comment]
Do you have a console.log?

**Comment by eightyeight** [comment]
Issue wasn't reported by me - [here's](https://www.reddit.com/r/gamedev/comments/3bv7oq/torque_3d_37_released_linux_opengl_client/cspvouc) the original post. Should have asked them for a console log.

**Comment by Azaezel** [comment]
@eightyeight : that one was https://github.com/GarageGames/Torque3D/pull/1342 and confirmed by the poster as functional.
