### ISSUE TITLE
'<hash_map> is deprecated and will be removed' in convexDecomp library

### ISSUE THREAD

**Issue by eightyeight** [GarageGames/Torque3D#1368]
When compiling with VS2015 community:

> Error	C2338	`<hash_map>` is deprecated and will be REMOVED. Please use `<unordered_map>`. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning. (compiling source file E:\code\Torque\3D\Engine\lib\convexDecomp\NvRemoveTjunctions.cpp)	convexDecomp	c:\program files (x86)\microsoft visual studio 14.0\vc\include\hash_map	17

[This](https://code.google.com/p/convexdecomposition/) is the library we're using, and [here](http://codesuppository.blogspot.com.au/2009/11/convex-decomposition-library-now.html) is a blog post about it (note, the author has deprecated the library).

**Comment by eightyeight** [comment]
It looks like the library is only used in a single file, `ts/tsMeshFit.cpp`. And removing it has no effect. So I think the fix here is to remove both `tsMeshFit.cpp` and the entirety of `lib/convexDecomp`.

**Comment by eightyeight** [comment]
Scratch that. The file isn't _used_ anywhere... but it defines console methods. [Example.](https://github.com/GarageGames/Torque3D/blob/86e0e67496f4d1ee5b7d6378739483e441567a83/Engine/source/ts/tsMeshFit.cpp#L818)

**Comment by JeffProgrammer** [comment]
unordered_map is C++11. Ready to transition to the modern STL yet or still supporting < VS2013 ?

**Comment by eightyeight** [comment]
Tell that to @dottools. This can probably solved reasonably easy with a `#define` but I'm loath to modify the library. On the other hand, it's deprecated, so I doubt it has been (or will be) updated independently of us.

I was hoping to be able to just get rid of it. The alternative might be to see if we can replace it with a more up-to-date library.

Orrrrr we could just modify it.

**Comment by Azaezel** [comment]
Going by https://code.google.com/p/convexdecomposition/source/browse/#svn%2Ftrunk doesn't look like she's been touched since 2009. Doubt modifying it's an issue.
