### ISSUE TITLE
sdl2 menu bar causing fatal assertions (windows)

### ISSUE THREAD

**Issue by Azaezel** [GarageGames/Torque3D#1384]
Sdl2 menu bar, specifically in a mission (so gui editor works) causes a fatal assertion. callstack:

 	Development_DEBUG.exe!dStrcmp(const char * str1, const char * str2) Line 62	C++
>	Development_DEBUG.exe!MenuBar::updateMenuBar(PopupMenu * popupMenu) Line 115	C++
 	Development_DEBUG.exe!MenuBar::removeObject(SimObject * obj) Line 69	C++
 	Development_DEBUG.exe!cm_SimSet_remove(SimSet * object, int argc, ConsoleValueRef * argv) Line 937	C++
 	Development_DEBUG.exe!cm_SimSet_remove_caster(SimObject * object, int argc, ConsoleValueRef * argv) Line 929	C++
 	Development_DEBUG.exe!CodeBlock::exec(unsigned int ip, const char * functionName, Namespace * thisNamespace, unsigned int argc, ConsoleValueRef * argv, bool noCalls, const char * packageName, int setFrame) Line 1945	C++

equates to:

https://github.com/GarageGames/Torque3D/blob/c152ae86f3f09b3c1d736954b352723d274582f1/Engine/source/platformSDL/menus/menuBarSDL.cpp#L115
to
https://github.com/GarageGames/Torque3D/blob/9bf6e0f8f499d3ed910fce357d70eaff59ffee39/Engine/source/core/strings/stringFunctions.h#L61

**Comment by Azaezel** [comment]
revising that: rapidfire F10 (bringing up/ closing the gui editor) does still break after all...

**Comment by Azaezel** [comment]
further testing: happens on linux side as well.

**Comment by Areloch** [comment]
Fixed this with my menubar pr.
