### ISSUE TITLE
GuiControl::setVariable(const char *value) unable to take type

### ISSUE THREAD

**Issue by Azaezel** [GarageGames/Torque3D#1408]
Recently rolled in https://github.com/GarageGames/Torque3D/commit/77b9600303ac952cd3a5153ce2cbf5809d5034b3#diff-e4ea6d75e6c53e52a5cc5049e7cd21ae

Broke an old code-share http://www.garagegames.com/community/forums/viewthread/38929/1#comment-303162

potential resolutions:
1) revert back to
   if ( mConsoleVariable[0] )
      Con::setVariable(mConsoleVariable, mTextBuffer.getPtr8());
2) add a StringBuffer flag defaulting to non-formated.
3) a brighter idea.

**Comment by eightyeight** [comment]
4) fix the old shared example to work with the way the class works now?

**Comment by Azaezel** [comment]
https://github.com/GarageGames/Torque3D/blob/development/Engine/source/gui/controls/guiTextEditCtrl.cpp#L1537 assuming it's not silently busted already. Which... http://forums.torque3d.org/viewtopic.php?f=15&t=339#p2957 yeah...

**Comment by eightyeight** [comment]
Option 1) is looking attractive

**Comment by Azaezel** [comment]
It'd be quickest, surely. Two was listed since adding method options is a bit more self-documenting than looking up usage-cases.
