### ISSUE TITLE
Move::Move() is not properly initializing bool trigger[MaxTriggerKeys];

### ISSUE THREAD

**Issue by pacomont** [GarageGames/Torque3D#1415]
Just a silly thing...They are assuming MaxTriggerKeys == 6
Actual code:  

```
   trigger[0] = false;
   trigger[1] = false;
   trigger[2] = false;
   trigger[3] = false;
   trigger[4] = false;
   trigger[5] = false;
```

Proposed code:

```
for (S32 i = 0; i< MaxTriggerKeys; i++)
trigger[i] = false;
```

**Comment by eightyeight** [comment]
Seems totally reasonable. I'm sure a PR for that would get accepted in a flash :).

**Comment by chaigler** [comment]
Looks like the fix for this was merged in last year. Should this be closed?

**Comment by Areloch** [comment]
Ah! Indeed it should, thanks!
