### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by jamesu** [GarageGames/Torque3D#1422]
Problem: Torque3D does not support ipv6.

Considering the global exhaustion of ipv4 addresses, and the increasing likelihood of future networks actually moving to ipv6, it makes sense for torque to support ipv6 in the networking stack. From what I gather this requires changing argument types and factoring in ipv6 addresses.

**Comment by eightyeight** [comment]
Definitely. This sounds like fun :sweat_smile:

**Comment by JeffProgrammer** [comment]
"fun" :^)

**Comment by kynora** [comment]
Not fun at all, because now we run out of addresses!!
And iOS 9 require only IPv6 only.
https://developer.apple.com/news/?id=05042016a

I start to learn too about IPv6,

**Comment by JeffProgrammer** [comment]
Wouldn't worry tooooo much yet, considering that this engine barely runs on anything other than Windows or Linux, but yeah, should be updated ;)

**Comment by Areloch** [comment]
Handled with #1817
