### ISSUE TITLE
terrain textures fubared on linux

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1437]
On Linux the terrain detail textures seem to be gone:
Broken:
http://imgur.com/GPxG8nT
Normal:
http://imgur.com/8MOzCjl

actual 3.8 version compiled with opensuse cmake and ninja

**Comment by BadFactor** [comment]
Looks weird, but i think this is why u doesnt  used ubuntu linux. Instead u used suse linux Maybe.

**Comment by JeffProgrammer** [comment]
saying to not use Ubuntu because this happens to be broken is just ridiculous and purist. This is an actual issue. Can confirm it happens on OSX.

**Comment by Calinou** [comment]
Terrain textures appear correctly for me in Uebergame 1.0.4.0, which uses Torque3D. They did not in Uebergame 1.0.3.5.

**Comment by Duion** [comment]
I think this has been fixed some time ago.

**Comment by JeffProgrammer** [comment]
yeah there's been some opengl fixes since way back when.
