### ISSUE TITLE
Unable to compile v3.8 with VS2015 [fix included]

### ISSUE THREAD

**Issue by Krakean** [GarageGames/Torque3D#1449]
When compiling, build log reports issues with dxerr.lib and __vsnprintf function.
As an workaround, add this line:
  int (WINAPIV * __vsnprintf)(char *, size_t, const char*, va_list) = _vsnprintf;
in gfxD3D9Shader.cpp after #include "gfx/D3D9/gfxD3D9Device.h"

**Comment by bigmonkgames** [comment]
Fix doesn't seem to be working for me.

**Comment by bigmonkgames** [comment]
My temp fix is in:
Torque3D\Engine\source\gfx\D3D9\gfxD3D9Device.h
comment out 
// #include <DxErr.h>

\Torque3D\Engine\source\gfx\D3D9\gfxD3D9Shader.cpp
under if ( res != D3D_OK && smLogErrors )
comment out
 //     Con::errorf( "GFXD3D9Shader::_compileShader - Error compiling shader: %s: %s (%x)", 
//         DXGetErrorStringA(res), DXGetErrorDescriptionA(res), res );

**Comment by Krakean** [comment]
>Fix doesn't seem to be working for me
Well, I was compiling it using Release mode, didn't tested Debug mode though.

**Comment by blackwc** [comment]
I don't get these errors in latest dev branch.

**Comment by TheMasterMaind** [comment]
I get the same error on the lastest version of the engine. Microsoft says the dxerror.lib is deprecated and should be dropped (DXSDK -> Windows SDK). For a workaround I used the same fix as @Krakean namely:

int (WINAPIV * __vsnprintf)(char , size_t, const char, va_list) = _vsnprintf;

i added this line after an including <windows.h> somewhere in mainLoop.cpp.

and the error goes away.

**Comment by mattiascibien** [comment]
As far as I know dxerr source code can be found on [this blog post](http://blogs.msdn.com/b/chuckw/archive/2012/04/24/where-s-dxerr-lib.aspx) and is under MsPl license. I can tra to include chat if you with.

**Comment by TheMasterMaind** [comment]
@mattiascibien Thx.
I already found this Blog post myself but hadn't the time to test it yet. IMO the DXERR lib should be completely dropped than just including a workaround. I haven't had the time to actually search the code where the lib is actively used but it should be easy to do so or to replace it with an alternative.

**Comment by mattiascibien** [comment]
i Will tra to cheek as I wait to hear from the devs too.

**Comment by TheMasterMaind** [comment]
Yea me too.
Am 30.12.2015 11:05 schrieb "Mattias Cibien" <notifications@github.com>:

**Comment by Azaezel** [comment]
Should be resolved by http://forums.torque3d.org/viewtopic.php?f=40&t=473 if ya'll want to help beat that up so we can get that in.

**Comment by Areloch** [comment]
Resolved via PR #1566
