### ISSUE TITLE
Effect quality list is blank in Empty template [v3.8]

### ISSUE THREAD

**Issue by Krakean** [GarageGames/Torque3D#1450]
Just compiled v3.8, and this is what I see in effects quality list: https://gyazo.com/c5d45702d53578f725c6aaa62ce68466
Is it OK or an issue?

**Comment by Areloch** [comment]
Sorry for taking so long to respond to this. It was a known thing for the options menu(it used to control stuff but at some point it was removed. Waaaay long ago.)

The template template is going to yield a completely overhauled options menu(should be merged in this week) so I'll close this issue.
