### ISSUE TITLE
Bullet shells bounce off water

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1458]
The bullet shells do not sink into water blocks, but stay on top of the surface like the water was a solid wall.

**Comment by eightyeight** [comment]
Obviously bullet shells float!

**Comment by blackwc** [comment]
[relevant](https://github.com/GarageGames/Torque3D/blob/development/Engine/source/T3D/debris.cpp#L44)

**Comment by Azaezel** [comment]
I'd more eyeball the side effects of stripping https://github.com/GarageGames/Torque3D/blob/8253bcc343d682223efc20c58f4c0bd44fd07c5f/Engine/source/environment/waterObject.cpp#L209 on down to it's own type

**Comment by blackwc** [comment]
aslo [relevent](https://github.com/GarageGames/Torque3D/blob/development/Engine/source/T3D/debris.cpp#L762)
