### ISSUE TITLE
recurseDumpDirectories trims characters where it shouldn't

### ISSUE THREAD

**Issue by blackwc** [GarageGames/Torque3D#1467]
[scanModules](https://github.com/GarageGames/Torque3D/blob/1a009d6dd31b66832de3b67e76465ad1f313a9dc/Engine/source/module/moduleManager.cpp#L164) will fail because it attempts to scan "rt" rather than "art."

**Comment by Areloch** [comment]
for #2, it looks like a bug with the recurseDumpDirectories call, where it trims characters where it shouldn't.

Thanks for spotting that, I'll have a PR made for it today

**Comment by Areloch** [comment]
Can you test #1469 and make sure it fixes issue #2 for you?

**Comment by blackwc** [comment]
I edited this issue to just be about the recurseDumpDirectories bug. Don't know what I was thinking combining two separate unrelated issues like that in one bug report.

**Comment by blackwc** [comment]
@Areloch works for me

**Comment by blackwc** [comment]
#1469 fixed this. Closing.
