### ISSUE TITLE
WorldEditor::unselectObject Crashes when Input ID is Invalid

### ISSUE THREAD

**Issue by Ragora** [GarageGames/Torque3D#1479]
Relatively simple issue, the engine will crash because this code fails to return if the input obj is NULL:

https://github.com/GarageGames/Torque3D/blob/development/Engine/source/gui/worldEditor/worldEditor.cpp#L2834

This stack is generated: http://pastebin.com/nUzFJN5u
So it pretty much just attempts to make a call against a NULL pointer if you don't give unselectObject a valid ID :) (Try EWorldEditor.unselectObject(0))

It also looks like you probably have similar issues floating around in things like selectObject, as well.

**Comment by Ragora** [comment]
Fixed my line ending issues (which is why I didn't make a PR initially) and put them in a pull request at #1480

**Comment by eightyeight** [comment]
For future reference, we usually keep issues open until their associated PR is merged :)

**Comment by Ragora** [comment]
Mostly habit from a previous codebase, pretty much the PR was the issue unless you didn't have the code for it. But I'll remember that, thanks!

**Comment by eightyeight** [comment]
All good! Not a problem. We don't typically create issues when a PR comes in directly - sometimes that wouldn't even make sense, like for a new feature. We keep issues open while a PR is happening because the PR might end up being rejected for various reasons, but the issue may still remain.
