### ISSUE TITLE
PopUp Dialog bottom border overlap on OpenGL/D3D11 mode

### ISSUE THREAD

**Issue by rasteron** [GarageGames/Torque3D#1485]
Hi,

Just a small issue that I'm seeing on GuiWindowCtrl with PopUp Dialog when switching to OpenGL renderer. I also have to mention Timmy's D3D11 renderer/build as it is doing the same and for future reference.

![opengl-dx11-gui-issue](https://cloud.githubusercontent.com/assets/3676827/11893419/6b5a31b2-a5ab-11e5-8ebe-3ebce4aa8edd.jpg)

**Comment by rextimmy** [comment]
Oh yes i have noticed this and forgot to add it to the list, cheers for the reminder. It's gotta be the shaders for the fixed function replacement causing this, as both d3d11 and the GL one's are almost identical. Will look into this.

**Comment by rasteron** [comment]
Hey sure thing Timmy and sounds great! thanks.

**Comment by rextimmy** [comment]
This issue can be closed now, see latest dev branch for fix above.

**Comment by rasteron** [comment]
Awesome thanks :)
