### ISSUE TITLE
Crash When Selecting Camera And Material Editor Is Open

### ISSUE THREAD

**Issue by SteveYorkshire** [GarageGames/Torque3D#1486]
Does exactly as it says on the tin.
When in the editor in player view and you try and select the camera, Torque3D will crash if the Material Editor is open. Not really an important bug, just an annoying one when you forget to switch out of Material Editor first.

**Comment by John3** [comment]
Hello @SteveYorkshire 

I tested this bug in a new clean t3d development branch, and I don't have this issue. Please can you see the video and tell me if correct the steps I do?

<a href="https://drive.google.com/file/d/0B9GUwtDHCp_eQV9kZmVhbFM0Tlk/view?usp=drivesdk">https://drive.google.com/file/d/0B9GUwtDHCp_eQV9kZmVhbFM0Tlk/view?usp=drivesdk</a>

If is correct can we close this? @Areloch

**Comment by Areloch** [comment]
Took a look at this m'self, and i got the crash to occur and PR'd a fix. If you or steve can test and affirm it, I can roll it in.

**Comment by John3** [comment]
Ok, I modified Engine/source/T3D/shapeBase.cpp as you can see in the following image. Clean environment, new project, last development branch....

<img src="http://i.imgur.com/T96PUdG.png"/>

And as you can see in the following image ended correctly.

<img src="http://i.imgur.com/54lk8YB.png"/>

I did the same test without issue.

**Comment by Areloch** [comment]
Fixed per the PR.
