### ISSUE TITLE
dragCoefficient misspelt 6 times over 2 scripts

### ISSUE THREAD

**Issue by SteveYorkshire** [GarageGames/Torque3D#1501]
dragCoeffiecient??? One "e" too many. Should be "dragCoefficient"

Offending entries:
https://github.com/GarageGames/Torque3D/blob/development/Templates/Full/game/art/datablocks/weapons/rocketfx.cs#L31
https://github.com/GarageGames/Torque3D/blob/development/Templates/Full/game/art/datablocks/weapons/rocketfx.cs#L31
https://github.com/GarageGames/Torque3D/blob/development/Templates/Full/game/art/datablocks/weapons/grenadefx.cs#L301
https://github.com/GarageGames/Torque3D/blob/development/Templates/Full/game/art/datablocks/weapons/grenadefx.cs#L465
https://github.com/GarageGames/Torque3D/blob/development/Templates/Full/game/art/datablocks/weapons/grenadefx.cs#L633
https://github.com/GarageGames/Torque3D/blob/development/Templates/Full/game/art/datablocks/weapons/grenadefx.cs#L848

Happens 6 times but only 1 has a setting that is not zero. Not handy if you're gonna copy and paste example scripts though. ;)

**Comment by ztb1020** [comment]
I made fixes to all of these.
