### ISSUE TITLE
console spam when netGraph open

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1503]
If you open the netGraph and then later look into console.log you will see console spam related to netGraph like:
core/art/gui/netGraphGui.gui (203): Unable to find object: 'ServerConnection' attempting to call function 'getGhostsActive'
core/art/gui/netGraphGui.gui (211): Unable to find object: 'ServerConnection' attempting to call function 'getPing'
core/art/gui/netGraphGui.gui (212): Unable to find object: 'ServerConnection' attempting to call function 'getPing'
core/art/gui/netGraphGui.gui (213): Unable to find object: 'ServerConnection' attempting to call function 'getPacketLoss'
core/art/gui/netGraphGui.gui (214): Unable to find object: 'ServerConnection' attempting to call function 'getPacketLoss'

**Comment by John3** [comment]
what t3d version/commit are you using? can you test in the last commit dev? I don't have this errors in the console.

**Comment by Areloch** [comment]
Also not seeing this in devhead.

**Comment by Duion** [comment]
Then I may have broken it or it has been fixed already, I use 3.8 still.

**Comment by John3** [comment]
I tested this in a clean v3.7 and clean v.3.8, without issue.
