### ISSUE TITLE
‘vsprintf’ was not declared in this scope

### ISSUE THREAD

**Issue by practicing01** [GarageGames/Torque3D#1515]
Merged latest development: /Engine/source/core/stream/stream.cpp:131:52: error: ‘vsprintf’ was not declared in this scope
    const S32 length = vsprintf(buffer, format, args);

**Comment by Azaezel** [comment]
try const S32 length = dVsprintf(buffer, sizeof(buffer), format, args);

**Comment by practicing01** [comment]
Ok, after that I get /Engine/source/math/mathUtils.cpp:1850:90: error: explicit qualification in declaration of ‘void MathUtils::mBuildHull2D(Vector<Point2F>, Vector<Point2F>&)’
 void MathUtils::mBuildHull2D(const Vector<Point2F> _inPoints, Vector<Point2F> &hullPoints)

**Comment by practicing01** [comment]
Ok fixed that by removing "MathUtils::" from the definition.
