### ISSUE TITLE
specular sliders are switched

### ISSUE THREAD

**Issue by Alex-doc** [GarageGames/Torque3D#1537]
I've just noticed that the specular sliders are now switched:
[shadergen](https://github.com/GarageGames/Torque3D/blob/908be4818f7e5de23f2070d18ed4df0f4dfc5ddf/Templates/Full/game/tools/materialEditor/gui/guiMaterialPropertiesWindow.ed.gui#L2004)
[editor slider value](https://github.com/GarageGames/Torque3D/blob/908be4818f7e5de23f2070d18ed4df0f4dfc5ddf/Engine/source/lighting/advanced/hlsl/deferredShadingFeaturesHLSL.cpp#L163)

Same for the specPower should be /128 in shaderGen and vice versa

**Comment by Lopuska** [comment]
Thanks Alex ;)

**Comment by Lopuska** [comment]
Fixed by @Azaezel
