### ISSUE TITLE
AMD GPUs and fullscreen windows

### ISSUE THREAD

**Issue by RoundedIcon** [GarageGames/Torque3D#1543]
#1513
AMD and whatever method torque uses to push a fullscreen window do not get along. Part of this issue could stem from Windows 10 / Crimson drivers that seem to hate torque3d with a passion, but this has been a problem for as long as I can remember.

**Comment by Areloch** [comment]
Just to double-check:

This is in DirectX, and are you using the latest drivers? Gunna get my hands on an AMD GPU to do some testing on this this weekend, so I just wanna try and get as close to your case as possible for replication.

**Comment by RoundedIcon** [comment]
This is with DirectX and the 16.2 Crimson driver. I haven't tested this on the latest driver (16.3?) yet.

**Comment by Azaezel** [comment]
there's a bit of card detection work in https://github.com/GarageGames/Torque3D/pull/1559 if you want to throw that at it, and see if that clears the issue up

**Comment by RoundedIcon** [comment]
That seems to have fixed the more noticeable problems. I will test it more extensively in a little while.
