### ISSUE TITLE
codeBlock.cpp: Bad DSO Condition?

### ISSUE THREAD

**Issue by Ragora** [GarageGames/Torque3D#1557]
Just a bit ago I was looking over how DSO's are processed and I noticed this line:

https://github.com/GarageGames/Torque3D/blob/development/Engine/source/console/codeBlock.cpp#L438

It seems to indicate that the engine just inserts a blank into the string table when you've read bad string table offsets from the DSO file. Shouldn't this indicate an error condition that the engine might want to instead ditch the DSO and print an error for? I'm not wholly familiar with how the engine is operating (as this may actually be desirable behavior for reasons I can't quite see?) otherwise I would've made this a pull request.

**Comment by dottools** [comment]
Unless it can be proven to be broken I err on the side of caution for any changes to those critical parts of the engine. For all I know that's actually a feature to cause it to insert an empty string string table entry upon exceeding the global string segment boundaries. @jamesu would probably know the real answer to that since he's familiar with the console and scripting subsystem code.

**Comment by Ragora** [comment]
The problem there is that then it means that the DSO is probably bad in some way (not a DSO if you somehow got to this point or its corrupted, etc).

**Comment by jamesu** [comment]
This code is specifically regarding the ident table which is used for named object references and such. The ident table just piggy backs onto the global string table to store names.

 If I recall correctly usually this sort of check is to filter out strings present in the function stringtable as opposed to the global stringtable (which are both separate), but as far as I can tell all idents get written to the global table so this check shouldn't be necessary. This is pretty old code so I think likely its one of those redundant checks which crop up after you change the design of the scripting engine a few times. I suggest placing a breakpoint there are double checking to make sure its not used in a typical case though. ;)

One a sidenote I mostly nuked this code in "Torquescript 2" as there I have a consolidated script value system instead which is simply read from the codeblock stream.

**Comment by Areloch** [comment]
As we'd integrated James' changes, this likely isn't really relevant at this point unless we spot it causing problems. I'll go ahead and close this issue unless we run into this again.
