### ISSUE TITLE
Linux Binary Dist includes only Windows Executables

### ISSUE THREAD

**Issue by italic-r** [GarageGames/Torque3D#1561]
I downloaded the 3.8 Linux binary distribution and extracted it only to find Windows executables. Is this intended? I wanted to build it locally, but it requires cmake 2.8.12, and Centos 7 is locked to 2.8.11. Getting cmake built and integrated with my system is far more trouble than it's worth and potentially breaks the system, so I need to avoid that.

Thanks

**Comment by TheDushan** [comment]
Easy way is to manualy change hardcored version inside "CMakeLists.txt"

Inside "Torque3D/CMakeLists.txt" you have there "cmake_minimum_required (VERSION 2.8.12)
". That is on line "1", you cannot miss it.
lower that to version what your cMake for CentOS is supporting and that will solver your problem.

Thanks for reporting this, I hope that someone with write access will edit "CMakeLists" and fix that
:)

**Comment by Italic-** [comment]
The issue with that is some build systems require features introduced in 2.8.12. I've tried to build other projects, like Open Broadcast Software, by lowering the required cmake version, only to run into unavailable or unsupported features. I can't seem to find a full version of the changelog for 2.8.12, but this is as close as I can get: https://cmake.org/pipermail/cmake/2013-October/056020.html

I'm only an amateur builder and don't know the specifics of cmake. Someone more knowledgeable of Torque's build system would have to tell me if 2.8.12-specific features are being used.

**Comment by TheDushan** [comment]
No.
AFAIK, none of improvements what are introducted with "2.8.12" versions are used while generating build solution
Also, others used "2.8.12" version because they thought that it is the lowest known working version number for all platforms.

**Comment by JeffProgrammer** [comment]
If i were you I would go download a newer CMake from CMake.org. Obviously this is the problem with Linux package managers. They do not keep up to date on stuff. We are now at Cmake 3.5 yet for some reason the package manager you are using is still on 2.x. I would personally advocate for completely dropping 2.x support as it is old.

**Comment by Areloch** [comment]
Yeah, I was just about to link https://cmake.org/download/

I'd say go and try and grab and use the latest binary from there first before having to worry about hacking in support for older versions. 

If that doesn't work, we can take it from there.

**Comment by Italic-** [comment]
I didn't realize I could download premade binaries for cmake... 

Centos 7 has been bugging me because of this lock on extremely old packages. I can understand the need for stability and reliability, but reverting a package to an older version than in the previous release of centos is just ridiculous. I will go with the premade binaries for now and contemplate my choice of distro later. Thanks everybody!

**Comment by Areloch** [comment]
No problem :)

Let us know if that does, indeed work for you. As for the issue's namesake, that was likely an upload issue on my part, I do apologize. I'll re-upload the linux binaries this weekend. Thanks for the spot on that :)

**Comment by Italic-** [comment]
I downloaded cmake 3.5 binaries and it seems to build Torque no problem. Configuring in cmake gives no errors, and I can build the engine and get into the editor. Thanks! I also got OBS built tonight, so two birds with one stone.

**Comment by Areloch** [comment]
Great to hear!

I'll see to it that the instructions for building T3D on linux link to the downloads for CMAKE to avoid this kind of confusion in the future. When we get to implementing the Project Manager 2.0, those binaries can just be included in there as well to make doubly sure :)

And as said before, I'll get the linux binaries re-uploaded this weekend.

**Comment by Italic-** [comment]
On a related note, I changed the required version to 2.8.11 and it configured and built without issue. It seems like either way would work. As far as I know, Centos 7 is the only one with cmake 2.8.11; even Debian stable is newer than this. Now that I know cmake binaries can be downloaded, I don't have a need for projects to maintain a low minimum. 

Out of curiosity, is there a minimum supported GCC?
