### ISSUE TITLE
Touchscreen support with game template

### ISSUE THREAD

**Issue by TheDushan** [GarageGames/Torque3D#1564]
I can elaborate, if needed

**Comment by Areloch** [comment]
If you have more information, you need to elaborate on what you're going for. It doesn't really help anyone if you CAN elaborate, but require being asked to elaborate further before you do. That tends to lead to confusion and extra steps to understanding the issue or proposal.

So yes, please elaborate.

**Comment by John3** [comment]
Can we close this "issue"? Is pointless have something like this.

**Comment by Areloch** [comment]
Suggestions for improvements can also be made here, so that's not a problem, but this wasn't ever elaborated on, so I guess I'll close this for now.

**Comment by John3** [comment]
is not about the improvements, is about nonexistent description. Thanks.
