### ISSUE TITLE
Integrate Torque2D

### ISSUE THREAD

**Issue by TheDushan** [GarageGames/Torque3D#1565]
I can elaborate, if needed

**Comment by dottools** [comment]
This would be possible once T2D switches graphics operations to a `GFX` compatible subsystem and use the same `audio` and `console` subsystems. And of course platform code between both engines need to match too. Once that happens then you could literally copy all of T2D's 2D gamecore and components source files into say a `T2D/` directory under T3D's `engine/source/` directory and ta-da instant 2D support.

This would allow T3D to support everything T2D can do while at the same time keep T2D separate as a dedicated 2D game engine as T2D is extremely resource lite and very fast performance wise on mobile platforms. While T3D is currently considered a resource hog and performance monster even on medium end game machines which requires a pretty hefty graphics card.

**Comment by TheDushan** [comment]
like I said, I can elaborate if needed

**Comment by Areloch** [comment]
As covered in the other issues, please be clear and elaborate on the issue when submitted to minimize confusion.
