### ISSUE TITLE
NearClip distance wrong with OpenGL rendering

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1572]
The nearClip distance that can be set in the level-Info object seems to be wrong when switching to OpenGL rendering.
By default the value is set to 0.1, but when you switch to OpenGL you have to set it to 0.2 to achieve the same effect for the nearClip distance.
I noticed that I could suddenly see meshes near my character when I switched to OpenGL, which were not visible in DirectX.

**Comment by andr3wmac** [comment]
Projection Matrix for OpenGL likely uses a [0:1] depth range instead of [-1:1].

**Comment by Duion** [comment]
Can this be solved using an if condition to switch those values depending on renderer?

**Comment by Areloch** [comment]
Dealt with in #1574
