### ISSUE TITLE
Empty template not working with deferred shading

### ISSUE THREAD

**Issue by lukaspj** [GarageGames/Torque3D#1588]
I just downloaded a clean version of Torque 3D, latest version.
I created a project based on 'Empty', and it didn't work, but the 'Full' version worked just fine.
Turns out the Empty template was missing a bunch of shaders and stuff like that for the deferred shading pipeline. I don't know exactly how much it missed, but it lacked "deferredShading.cs" for one.

**Comment by John3** [comment]
Yea confirmed.

**Comment by Azaezel** [comment]
https://github.com/GarageGames/Torque3D/pull/1603

**Comment by Areloch** [comment]
Fixed via #1603
