### ISSUE TITLE
T3D don't compile "epoxy/gl.h': No such file"

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1600]
Hi I just download the new version of torque3d I can't compile the damn thing hahaha

1>C:/Game Develop/Game Engine/T3D/Engine/source/gfx/gl/tGL/tGL.h(26): fatal error C1083: Cannot open include file: 'epoxy/gl.h': No such file or directory

I'm bit lose right now with all the changes but in the commit change I notice this "Merge pull request #1567: Added Epoxy in favor of GLEW" may be something was missing.

**Comment by Areloch** [comment]
Hey John, just to double check, is this windows or linux you're seeing this happen on?

**Comment by John3** [comment]
Windows 7

**Comment by JeffProgrammer** [comment]
What compiler/IDE are you using? VS2010? VS2015? MinGW?

**Comment by John3** [comment]
Oh sorry by lack of information Jeff. 

Clean Torque3D
Branch: Development
Windows 7
VS2010
Project Manager: Torque physics, OpenGL Rendering

**Comment by JeffProgrammer** [comment]
I've only tested with Visual Studio 2015, running Windows 7 Service Pack 1 w/ Platform Update. Epoxy should still be supported in VS2010.....hmm...

**Comment by Areloch** [comment]
Can you double-check your include paths for the project and that they include the epoxy paths:

(you engine directory)\Engine\lib\epoxy\include
(you engine directory)\Engine\lib\epoxy\src

**Comment by John3** [comment]
A clean t3d development branch with a new project and yes the epoxy folder is there with the include files. Are you try to say I need to include in my VS project the epoxy?

**Comment by Azaezel** [comment]
@John3 : it look like
http://i.imgur.com/Iy6WiIY.jpg ?

**Comment by Areloch** [comment]
Sorry, i meant in the project settings. You have your project settings where you set the include paths where it checks additional header files and the like.

So just open up the settings for the project(should be r-click on project > properties > C/C++ > General and then the Additional Include Directories field)

Want to see that those did indeed get added to the project when you generated it. That'll tell us where to look next, because it SHOULD be working correctly.

**Comment by JeffProgrammer** [comment]
@John3 are you using the project manager? If so you have to use CMake as I never wrote a project manager module for epoxy. Didn't realize folks were still using it. There's a CMake tutorial on the wiki if you run into trouble.

**Comment by John3** [comment]
oh, so I need to use cmake then haha, sorry but I was out for a few months I don't know that project manager is not using anymore. Sorry for the confusion guys, yes I now I need to add to the VS project to build... I just opened thinking that was a issue. The new people know PM is not using anymore? If it not a issue sorry, we can close this.

**Comment by John3** [comment]
Hmmm ok I use CMake 3.5.2, but still have error with epoxy. I just follow this guide to be sure http://wiki.torque3d.org/coder:compiling-in-windows#toc6 and select OpenGL. I build without OpenGL and it works. With OpenGL I have this error:

http://pastebin.com/2WVnYbn1

**Comment by JeffProgrammer** [comment]
Looks like epoxy won't work with VS2010 as it doesn't have stdbool.h which is a C99 header:

http://stackoverflow.com/questions/8548521/trying-to-use-include-stdbool-h-in-vs-2010

**Comment by Areloch** [comment]
Apparently epoxy makes use of stdbool.h, which VS2010 does not support.

So going forward, if you want to make use of OpenGL, you'll want to jump up to 2012, 2013 or 2015, otherwise if you HAVE to use vs2010 for whatever reason, you can just go without OpenGL.

**Comment by John3** [comment]
Thanks! I have 2012 already. I use a lot vs2010 for the old versions of torque3d.

**Comment by JeffProgrammer** [comment]
@John3 sounds good. Let us know if it works out! :)

**Comment by John3** [comment]
Don't work vs2012 either hahaha so.. I suppose 2013 and up, good to know for the next release, is necessary to document this. So from now on CMake and vs2013.

**Comment by dottools** [comment]
You could [create your own stdbool.h](http://stackoverflow.com/a/14405759/139041) ;)

**Comment by John3** [comment]
Hahaha forget it dude thanks but this is not for me. All the new people don't need to fight with the engine. So, we can now document this as requirement for the new releases.

**Comment by Areloch** [comment]
Haha, yeah, we'll just figure for VS2013 as the minimum. If people absolutely have to have older than that, they're gunna be clever enough to work out SOME kind of solution :package: 

I'll update the wiki page for compiling on windows to mention the VS version req and go ahead and close this ticket.

Thanks for the spot on this, John, we all learned some nifty stuff from this :)
