### ISSUE TITLE
spinlight animation don't work

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1601]
I'm using the last develop version, the spinLight animation type from spotLight don't work, the last working version was from 3.8-RC. Something in between v3.8-RC and v3.8 broke this. I think we need to fixed before v4.

<img src="http://i.imgur.com/QjLW6tn.png"/>

**Comment by John3** [comment]
Ok try to tracking it down from here: https://github.com/GarageGames/Torque3D/compare/v3.8-rc...v3.8

Here is working as expect https://github.com/GarageGames/Torque3D/commit/58ae3316090413a402e3bdb3f45abd4582bf352e

Here is broke the SpinLight animation: https://github.com/GarageGames/Torque3D/commit/6e1d031ecd8eb184baf3a7be50b39d85bb45d8e4

**Comment by John3** [comment]
Ok. I sent a pull request, I tested and is working the light spin. I test my already made level still work without broking anything else.

**Comment by Areloch** [comment]
Fixed via PR, thanks for your hard work :D
