### ISSUE TITLE
unable to find object and then freezed for 1sec.

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1606]
whats this mean? Always when happen is freeze 1sec the engine.

<img src="http://i.imgur.com/vc6fHI1.png"/>

materialEditor.ed.cs
`   MaterialEditorPropertiesWindow-->subSurfaceCheckbox.setValue((%material).subSurface[%layer]);
   MaterialEditorPropertiesWindow-->subSurfaceColorSwatch.color = (%material).subSurfaceColor[%layer];
   MaterialEditorPropertiesWindow-->subSurfaceRolloffTextEdit.setText((%material).subSurfaceRolloff[%layer]);
   MaterialEditorPropertiesWindow-->minnaertTextEdit.setText((%material).minnaertConstant[%layer]);`

<img src="http://i.imgur.com/TE9aPuz.png"/>

**Comment by Areloch** [comment]
With deferred, subsurface scattering broke, so it was removed until it could be fixed. Az has a PR to re-implement a form of it here: #1582 
Go ahead and implement that(and comment out the subsurfaceColorSwatch, subSurfaceRolloffTextEdit and minnaertTextEdit lines) and see if that all resolves the notices and freeze you're seeing.

**Comment by John3** [comment]
Now is very smooth! :D I will keep testing... but I think its worked.

**Comment by John3** [comment]
yes resolved the console errors and the freeze. Thanks

**Comment by Areloch** [comment]
Resolved as per #1582
