### ISSUE TITLE
T3D don't compile - mathTypes.obj : error LNK2019:

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1618]
Hi don't know if is me :D with the last commits don't compile.

My last working commit was this.
https://github.com/GarageGames/Torque3D/commit/a2e0b1a163de1b0192c59d305e3dcaea16df2add

Then I pull 24 commit, the last is this.
https://github.com/GarageGames/Torque3D/commit/65f51a89d8e589bfc1836fc1b1db12ece689b0d4

- Development branch.
- Cmake (default options)
- Windows 7
- VS2010 xD

`1>------ Build started: Project: cleanT3Dproject1, Configuration: Debug Win32 ------
1>     Creating library C:/Menu/Game Develop/Game Engine/cleanT3D/My Projects/cleanT3Dproject1/buildFiles/CMake/Tools/CMake/Debug/cleanT3Dproject1_DEBUG.lib and object C:/Menu/Game Develop/Game Engine/cleanT3D/My Projects/cleanT3Dproject1/buildFiles/CMake/Tools/CMake/Debug/cleanT3Dproject1_DEBUG.exp
1>mathTypes.obj : error LNK2019: unresolved external symbol "public: class Point3F __thiscall RotationF::asEulerF(enum RotationF::UnitFormat)const " (?asEulerF@RotationF@@QBE?AVPoint3F@@W4UnitFormat@1@@Z) referenced in function "public: virtual char const * __thiscall ConsoleTypeTypeRotationF::getData(void *,class EngineEnumTable const *,class BitSet32)" (?getData@ConsoleTypeTypeRotationF@@UAEPBDPAXPBVEngineEnumTable@@VBitSet32@@@Z)
1>mathTypes.obj : error LNK2019: unresolved external symbol "public: void __thiscall RotationF::set(class AngAxisF,enum RotationF::UnitFormat)" (?set@RotationF@@QAEXVAngAxisF@@W4UnitFormat@1@@Z) referenced in function "public: virtual void __thiscall ConsoleTypeTypeRotationF::setData(void *,int,char const * *,class EngineEnumTable const *,class BitSet32)" (?setData@ConsoleTypeTypeRotationF@@UAEXPAXHPAPBDPBVEngineEnumTable@@VBitSet32@@@Z)
1>mathTypes.obj : error LNK2019: unresolved external symbol "public: void __thiscall RotationF::set(class Point3F,enum RotationF::UnitFormat)" (?set@RotationF@@QAEXVPoint3F@@W4UnitFormat@1@@Z) referenced in function "public: virtual void __thiscall ConsoleTypeTypeRotationF::setData(void *,int,char const * *,class EngineEnumTable const *,class BitSet32)" (?setData@ConsoleTypeTypeRotationF@@UAEXPAXHPAPBDPBVEngineEnumTable@@VBitSet32@@@Z)
1>C:\Menu\Game Develop\Game Engine\cleanT3D\My Projects\cleanT3Dproject1\game\cleanT3Dproject1_DEBUG.exe : fatal error LNK1120: 3 unresolved externals
2>------ Skipped Build: Project: INSTALL, Configuration: Debug Win32 ------
2>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 17 up-to-date, 1 skipped ==========`

**Comment by John3** [comment]
it seems that only supports vs2015 now..

**Comment by Azaezel** [comment]
using vs2013 this end. compiled fine this end. RotationF defintions are in new files. aee https://github.com/GarageGames/Torque3D/pull/1584/files
