### ISSUE TITLE
Is documented somewhere the coding standards?

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1619]
Is documented somewhere the coding standards?

I mean contribution guidelines...

- TorqueScript coding standard and style guide.
- C++ coding standard and style guide.
- Documentation and Wikis standard.

**Comment by dottools** [comment]
[Code Style Guidelines](http://wiki.torque3d.org/coder:code-style-guidelines), mostly C++ specific.

**Comment by John3** [comment]
thanks! from the [Code Style Guidelines](http://wiki.torque3d.org/coder:code-style-guidelines)
> While some points covered deal strictly with the C++ source code, many of the style principles can be used with the scripts as well.

So I will close this. If someone thinks something is missing from the coding style we can open it again.
