### ISSUE TITLE
Crash! - new datablock from DefaultPlayerData.

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1646]
The game crash when you create a new datablock and copy his data from DefaultPlayerData. Save, exit the level, and re-enter the level, it crash. To avoid the crash when you reenter the level is needed to clean your managedDatablocks.cs

**Caused by:**
Commits on Jun 2, 2016 - 89672ea

**VS2015 log**
show this from compiledEval.cpp
<img src="http://i.imgur.com/d0hZ4PQ.png"/>

**console.log**
`tools/shapeEditor/main.cs (291): Unable to find object: '0' attempting to call function 'delete'
20867 -> deactivatePackages
CDROP: 20869 IP:0.0.0.0:0
Exporting server prefs...
Time spent in toggleEditor() : 0.297 s
Exporting server prefs...
SimGroup::addObject - (280440944) can't add self!
Executing core/art/datablocks/datablockExec.cs.
Executing core/art/datablocks/camera.cs.
Executing core/art/datablocks/markers.cs.
Executing core/art/datablocks/defaultparticle.cs.
Executing art/ribbons/ribbonExec.cs.
Executing art/ribbons/ribbons.cs.
Executing art/particles/managedParticleData.cs.
Executing art/particles/managedParticleEmitterData.cs.
Executing art/decals/managedDecalData.cs.
Executing art/datablocks/managedDatablocks.cs.
Exception thrown: read access violation.
currentNewObject-> was 0xDDDDDDDD.`

**Comment by Azaezel** [comment]
try applying https://github.com/GarageGames/Torque3D/pull/1645

**Comment by John3** [comment]
I apply this PR #1645 and is still crash with this error

> T3D\Engine\source\gfx\gfxDevice.cpp(279,0): {Fatal} - There is a texture object leak
> T3D\Engine\source\gfx\gfxPrimitiveBuffer.cpp(54,0): {Fatal} - There is a primitive buffer leak

so I think this issue is somewhat related to this issue #1648
