### ISSUE TITLE
Crash! - There is a texture object leak

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1648]
Don't know how to reproduce this :( is random.

when I exit, the engine crash. I use this T3D version: commit 5122360

- CMake default options
- VS2015 debug
- Windows 7

http://pastebin.com/rzFaJU2v

> C:\T3D\Engine\source\gfx\gfxDevice.cpp(279,0): {Fatal} - There is a texture object leak, check the log for more details.

https://github.com/GarageGames/Torque3D/blob/development/Engine/source/gfx/gfxDevice.cpp#L278-L281

T3D\Engine\source\gfx\gfxPrimitiveBuffer.cpp(54,0): {Fatal} - There is a primitive buffer leak

**Comment by Areloch** [comment]
Looks like it's having some issues with loading DDS's?

Are you using any non-stock DDS files for textures?

**Comment by practicing01** [comment]
I'm getting this on app exit, after switching player models with setDatablock().

**Comment by John3** [comment]
I can confirm. To reproduce the error.
1) Select Camera. Move away a little
2) Select the player
3) In his property, changes his DefaultPlayerDatablock for other like DemoDatablock.
4) Save and exit

**Comment by Areloch** [comment]
Can you verify if you're still seeing this on latest devhead? I'm not able to replicate it with the 'spectate, swap player's datablock and exit' instructions now.

**Comment by John3** [comment]
Ok using the latest "35c4df3" if I use a new full template I can't reproduce this. For my test projects from old commits but now updated to the latest, I still having this problem.

**Comment by Areloch** [comment]
so brand new clean up to date template is ok, but a prior template copied up is not?

Any chance you could do a winmerge or some other comparison for a list of changed files with your build that's having the problem still?

**Comment by John3** [comment]
I did a winmerge, clean sharders, and still happen. I have other project (almost clean) with the same issue, I can shared if you want.

**Comment by John3** [comment]
here: https://drive.google.com/file/d/0B9GUwtDHCp_eRzFsTEhROFpJdlE/view?usp=sharing

**Comment by John3** [comment]
I download and compile torque3d v1 to poke around and this issue exist. 
See the issue: https://drive.google.com/file/d/0B9GUwtDHCp_eVXVoVWZOMm1JeUU

Don't know what this means XD hmmm It means it is already corrected in the lastest commit???

**Comment by Areloch** [comment]
Yeah, I did a clean development, used your build's game files, and couldn't replicate it with the above instructions of swapping the to the demoPlayer data. 

Does it happen on your side if you do the same? Clean build of devhead and just copy your above game's files into the dir with the clean devhead exe?

**Comment by Areloch** [comment]
As far as I can tell, between stock, the example old project, and az testing on his end, this is pretty much resolved. If anything else pertaining to it crops up, this can be re-opened.

**Comment by John3** [comment]
Hi Areloch, ok thanks.... I'm traveling since last week, maybe tomorrow I can test this.

**Comment by Areloch** [comment]
Ah, gotcha.  Yeah, lemme know if you find anything else.

**Comment by John3** [comment]
a bit late, but I can confirm this was resolved :D
