### ISSUE TITLE
Compile Error: "GCC: Unsupported Target CPU"

### ISSUE THREAD

**Issue by practicing01** [GarageGames/Torque3D#1649]
Linux, amd cpu.  This is happening with the latest dev.  This wasn't happening before and it doesn't happen on another linux/amd computer.

**Comment by JeffProgrammer** [comment]
what version of GCC are you using?

**Comment by Azaezel** [comment]
https://github.com/GarageGames/Torque3D/blob/7bba3ee2de610c2757bc70eba10db869bab72a85/Engine/source/platform/types.gcc.h#L139 that whats tripping?

**Comment by practicing01** [comment]
Gcc version 4.8.4 on both machines.  Yes that's the line where it's tripping balls.  Remember, this wasn't happening before, I was using the machine just fine untill I merged the latest dev.

**Comment by practicing01** [comment]
Fixed by commenting out this line: https://github.com/GarageGames/Torque3D/blob/510b726f6fa3aaeac1a4ed69aa88f918fa0315a7/Tools/CMake/torque3d.cmake#L39

**Comment by JeffProgrammer** [comment]
Failing on C++11...

I know this sounds silly but hear me out - Ive seen cases from my online research where the GCC and G++ versions did not match on the system. Can you type **g++ --version** since C++ is compiled with G++

That is odd, because C++11 is fully supported on 4.8.1+

**Comment by JeffProgrammer** [comment]
@practicing01 Found the fix :) replace i386 with __i386__ and it should work.

**Comment by Areloch** [comment]
Should be all corrected with #1677
