### ISSUE TITLE
SimObject Crashing

### ISSUE THREAD

**Issue by Phantom139** [GarageGames/Torque3D#165]
See the latter conversation here: http://www.garagegames.com/community/forums/viewthread/132437/1#comment-837289

Apparently there is an issue in the SimObject (and all of it's derived sub-objects) that leads to crashing. The reason for this is currently unknown, but this definitely needs to be looked in to.

**Comment by Areloch** [comment]
If this comes back up and we have better reproduction steps, we'll revisit, but for now I don't know that this issue is still active, so the ticket will be closed.
