### ISSUE TITLE
better bugs handling *Improvement*

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1651]
Will be better, have shorter frequently pre-release for better error handling. The user who want to use a more updated T3D can use this, then we can manage the new bugs in a better way if exist.

What latest dev? the questions here is, what the commit that you were using?

If we need to hunt down an old bug, we can go through fewer commits and not pages and pages of commits :dart: 

in the meantime I will be doing this in this post, hmm not sure how many times, but at least 2 times in a months. Please redirect the new people to my post if they want to use a more update version.

http://forums.torque3d.org/viewtopic.php?f=2&t=665

**Comment by Areloch** [comment]
I was actually pondering on doing this myself once 3.9 finalized. If you wanted to spearhead this though, that'd be pretty rad!

Thanks for your help : D

**Comment by eightyeight** [comment]
We used to have CI servers that provided this sort of thing. They were always pretty wonky though. Having something set up that worked properly would be :ok_hand:

**Comment by John3** [comment]
@eightyeight I remember we was using Jenkins....and what happened with the server? 

BTW how can we do a proper unit test? for TS or C++? I saw a few info scattered around but none seems to work.

@Areloch yea I can do that, right now for windows though until I have a build config for Linux

**Comment by John3** [comment]
Ok I think we can close this, basicatly the main point for this "issue for improvent" was to have/allow frecuently releases, and allow this way more test in the dev_branch, for those people that want to use this branch obviously not using the cmake/compile path...

- For the final users that want use the new features only in dev_branch.
- You need to upgrade to a new version, do a quick test of the features before upgrade your project.
- Finding bugs, If you are unsure about what commit broke X feature, just download the unofficial release, and do a test or compare between releases.
- Test others options like SDL, Bullet, etc
- Helping in report bugs "more easily", just reporting what "unofficial release" have the issue. Broken down the dev_branch in "little release chunks"
- Avoid have installed development dependencies (SDks), just download the dev_binary and load your scripts "exec("./myFolder/myScripts/myMainProyect.cs");" - if you are like me and have all your stuff in one folder for easy migrate your project.

**Forum:** http://forums.torque3d.org/viewtopic.php?f=2&t=665
**T3D v3.9:** http://forums.torque3d.org/viewtopic.php?f=2&t=665#p6230
**Unofficial binary releases:** https://github.com/John3/Torque3D_Unofficial/releases

We need at some point a properly configured CI... right now this can help.

**Comment by eightyeight** [comment]
> BTW how can we do a proper unit test? for TS or C++?

For C++ unit tests: http://wiki.torque3d.org/coder:unit-testing

I was working on a [unit testing framework](https://github.com/eightyeight/tasman) for TorqueScript and it's somewhat functional, but I never integrated it into the templates in any meaningful way.
