### ISSUE TITLE
Bitstream.cpp Fatal Out of range read

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1664]
I´m playing with the latest commit 64fab75

1) Open Empty terrain
2) Use the shape station01 
3) Move around
4) Crash with >Out of range read<

T3D\Engine\source\core\stream\bitStream.cpp(289,0): {Warning} - Out of range read

Windows7
Defaults options CMake + VS2015 Debug

**Comment by John3** [comment]
I revert to this commit dfb8f4f5e52f63519156c55e49a43fa2d82d5023 now it´s working =)

**Comment by Areloch** [comment]
Can you clarify the revert? You removed the dfb8f4f commit? Or you just reverted TO that commit?

**Comment by John3** [comment]
hey @Areloch :O sorry,  I went to an old commit dfb8f4f5e52f63519156c55e49a43fa2d82d5023.

**Comment by Areloch** [comment]
Are you still seeing this in devhead? I haven't been able to replicate it. If so, what are you doing when you say 'move around'? Are you moving away from the station? Towards it?

**Comment by John3** [comment]
same as here #1648 clean template don't have the issue. Old project have the problem, just move the station, the same happen with a rock, tree or any shape.

See the video:
https://drive.google.com/file/d/0B9GUwtDHCp_eTF96bGJXc3YwMHc

Here you can use the project 
https://drive.google.com/file/d/0B9GUwtDHCp_eRzFsTEhROFpJdlE/view

**Comment by John3** [comment]
Ok let me try identify the bug commit... I'm pretty sure is something in here
<img src="http://i.imgur.com/zUqWotd.png"/>

**Comment by John3** [comment]
Ok, I can confirm...

Last working commit: 810ac82eaee5e11c24236ebf499ac8ebfb1fb0d8
Caused by: 69244a8577d92a0662d8ac8a0aead851e8ef3f8c

**Comment by Areloch** [comment]
I think I know what it is. Mismatch in the pack/unpack. 

Can you go to this line: https://github.com/GarageGames/Torque3D/blob/development/Engine/source/T3D/tsStatic.cpp#L862
and after that, add a mPlayAmbient = stream->readFlag(); there and see if that sorts it for you?

**Comment by John3** [comment]
it works, I did a PR. Thanks!
