### ISSUE TITLE
No shadows in OpenGL

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1665]
I noticed that there are no shadows in OpenGL render mode.
The issue was not always there, it only recently got introduced for some people after some graphics driver update.
No idea when exactly the issue appeared, I do not use OpenGL that often, so maybe some people can switch to OpenGL and test it as well.

**Comment by John3** [comment]
I have shadow in my OpenGL. I use Nvidia =)

<img src="http://i.imgur.com/52wDMjp.png"/>

What you mean? can you show a pic?

**Comment by Duion** [comment]
Ok, seems to be an issue with my game and not the default Torque3D, false alarm.

**Comment by Duion** [comment]
Problem was caused by:
https://github.com/GarageGames/Torque3D/commit/223e9a8264820b2f64de28cbb131e881b03fe4be
and solved by:
https://github.com/GarageGames/Torque3D/commit/bc9033da2e51cbeb7722157d6c4da03cd29f002e
which I did not implement.
So now I have my shadows back, but also the problem why the fix was initially applied is back, meaning that the projection matrices do not look the same anymore in D3D and OpenGL.

**Comment by John3** [comment]
so I suggest you close this issue because is fixed and open other issue if not exist about the projection matrices.
