### ISSUE TITLE
Projection matrices wrong in OpenGL

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1666]
Recently I told Azaezel the projection matrices were wrong in OpenGL, they did not look the same as in DirectX, then he committed a fix for them:
https://github.com/GarageGames/Torque3D/commit/223e9a8264820b2f64de28cbb131e881b03fe4be
It solved the issue, but later I found out, that it breaks shadows in OpenGL, then later Jeff rolled it back, it fixed the shadows, but the projection matrices are wrong again:
https://github.com/GarageGames/Torque3D/commit/bc9033da2e51cbeb7722157d6c4da03cd29f002e

It is not that big of an issue, but it makes that the clipping distance is wrong. In my example, I have a player that uses realistic first person view, so it uses the full model in first person, but you can see pieces of the helmet if you look up, while it is not visible in DirectX rendering.

For reference it is the "nearClip" value in theLevelInfo object in your mission.
By default it is set to 0.1 for each level, which is a good distance, but if you switch to OpenGL it behaves like it would have been set to 0.05, so about half the value as in DirectX.

**Comment by JeffProgrammer** [comment]
does that have anything to do with the screen mapping coordinates being different between DX and OGL? I'm not entirely sure, but just throwing that out there.

**Comment by Duion** [comment]
The "fix" Azaezel contributed did solve it correctly, but it broke shadows,
I'm not an expert on this, but he seemed to know what the problem was.

2016-07-10 21:26 GMT+02:00 Jeff Hutchinson <notifications@github.com>:

**Comment by Azaezel** [comment]
to further clarify the tag from https://github.com/GarageGames/Torque3D/commit/bc9033da2e51cbeb7722157d6c4da03cd29f002e

Epoxy looks to handle the projection depth range so it behaves more like D3D, so this change was doubling up and causing problems. - which was breaking the skybox rendering since that operates at the extent of the viewdistance (ie max depth). Hence the reversion.
