### ISSUE TITLE
Missing entity.obj while compiling with VS2013 Pro on Windowns 10

### ISSUE THREAD

**Issue by xetra11** [GarageGames/Torque3D#1679]
When I follow the instruction in the tutorial I fail compiling the  "<projectname> DLL" project because of the following error:

> Fehler	133	error LNK1120: 1 nicht aufgelöste Externe	C:\Users\Falke\Google Drive\Workspace.cloud\Software Development\Torque3DTryout\Torque3D\My Projects\Tutorial\game\Tutorial_DEBUG DLL.dll	Tutorial DLL

> Fehler	132	error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""public: void __thiscall Component::setOwner(class Entity *)" (?setOwner@Component@@QAEXPAVEntity@@@Z)" in Funktion ""public: bool __thiscall Entity::addComponent(class Component *)" (?addComponent@Entity@@QAE_NPAVComponent@@@Z)".	C:\...\Torque3D\My Projects\Tutorial\buildFiles\VisualStudio 2012\projects\entity.obj	Tutorial DLL

When I look for entity.obj it is NOT within the path given at the second error message it is withing the build dist directory: 
> C:\...\Torque3D\My Projects\Tutorial\buildFiles\Link\VC2010.Debug.Win32\Tutorial DLL\entity.obj

I really tried a lot like comping with vs110 instead of 2013's vs120 and using another template project from the project manager - but always the same issues. I really want to get started but this blocks me for two days now :(

**Comment by John3** [comment]
Hi @xetra11 

1) What are you try to compile? Is a clean template?
2) What tutorial are you following?
3) What visual studio are you using?
4) Are you using the latest commit/dev?

You can download the latest binary from here:
- http://forums.torque3d.org/viewtopic.php?f=2&t=665 (Compiled by me, latest dev version)
- https://github.com/GarageGames/Torque3D/releases

If you want to compile please follow this tutorial.
- http://wiki.torque3d.org/coder:compiling-in-windows#toc6

Recently due the latest changes I recommend to use CMake and VS2015.

**Comment by John3** [comment]
Is easy with CMake, but if you still have doubt I can do a video tutorial.

**Comment by xetra11** [comment]
@ John3

Sorry for the lack of informations

1) I created an "Empty" Template project via ProjectManager
2) Following the official Doc -> http://docs.garagegames.com/torque-3d/official/content/documentation/Setup/FirstProject.html
3) Visual Studio 2013 Professional and having 2012 installed so I'm able to use vs110 which I tried to build with as well
4) I cloned the master and tried it with the pre-releases as well

I try to do it via CMake ! thanks for the guidance

**Comment by xetra11** [comment]
@John3 

After generating the project with the project manager I could not found a

>cd "C:\Torque3D\My Projects\Game\buildFiles\CMake"

CMake Folder there

**Comment by John3** [comment]
Ok I see. Don't worry. The official tutorial still valid, but not for compile.... we still moving to the "community official page"

So.... welcome! :D

Let me guide you:

Official repo: https://github.com/GarageGames/Torque3D 
Two main branches: 
- master with stable releases.
- development with last update of features. very stable some bugs.

New forum: http://forums.torque3d.org/
New page: http://torque3d.org/
New Wiki/Doc: http://wiki.torque3d.org/

Ok let give a few minutes to do a little guide and sorry for this lack of documentation, but this change are very recently.

**Comment by xetra11** [comment]
Ah wow I was still browsing on garagegames - did not now you guys moved

**Comment by John3** [comment]
Ok, I did this video just for you :D https://youtu.be/uh0EFeh-Fyk

**Comment by xetra11** [comment]
@John3  Thanks for the incredible effort! I'll work after that video and report if everything worked fine

**Comment by John3** [comment]
@xetra11 if you want to test OpenGL or DirecX 11 
See this steps:
https://youtu.be/09h72R4wm9Y

**Comment by xetra11** [comment]
@John3 
It works fine now. Just trying out some stuff to mybe reproduce the error. Trying to make without CMake and via VS again. But until now it works fine - really seems to got fixed with some patch in the development branch. Hopyfully that state will be declared stable asap and released!

**Comment by xetra11** [comment]
@John3 

Ok it seems that generating the template project via the project manager and opening the visual studio 2012 buildfiles results in some errors for me - or commonly for all mybe? Don't know.

I'll stick to the CMake solution u doced in the youtube video.
thank you !

**Comment by John3** [comment]
Basically is the same steps but CMake is more flexible, right now is more update CMake that Project Manager.

Project manager maybe replaced with CMake at the end. We not decide yet. Maybe we use Project Manager with cmake at the back end, don't know for sure.

But from now on I mean "Torque3D v3.9 and beyond" it will use CMake, until further notice.
