### ISSUE TITLE
Graphic glitches on OpenGL with rain

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1680]
I noticed that there are graphic glitches like lines crossing all over the screen if render mode is OpenGL and there is a precipitation object in the level like rain.
Can anyone confirm this?

**Comment by John3** [comment]
Ok, let my try. Can you give me a little more detail to ensure I doing right?

**Comment by JeffProgrammer** [comment]
Windows or Linux?
And your graphics card + driver version?

Thinking possibly regression from changing to dynamic VBO and on of the buffer update fns screwing up....

**Comment by Areloch** [comment]
I'd noted this on my laptop, which has an intel card, but my linux box and main desktop machine don't exhibit the behavior at all in OGL. Thinking it's gotta be something tied to the drivers. I know my laptop's drivers are out of date, I'll have to update them and try again.

Are your drivers up to date, Duion?

**Comment by Duion** [comment]
Yes, are up to date, I updated twice inbetween and the issue is still there, someone else on Linux also had the glitches.
It looks something like this, it is hard to screenshot since it just flickers up for a short moment: http://i.imgur.com/TCP8R27.jpg

**Comment by Areloch** [comment]
If you disable the splashes, does the glitching stop?

**Comment by Areloch** [comment]
Hey Duion, try adding    mMaxVBDrops = 5000; to the Precipitation constructor and trying again. That seemed to work for me.

**Comment by Duion** [comment]
Did not solve it for me.

**Comment by Duion** [comment]
I had someone else test it, he was on Linux, did not solve it for him as well.

**Comment by Areloch** [comment]
Tested on windows and Linux, no problems. I'll go ahead and close this unless we can better dial down on the problem, like OS, repo steps, etc.
