### ISSUE TITLE
Specular sliders broken

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1699]
Before the 3.9 update it was possible to adjust the specular strengths with those sliders in the material editor, but it no longer works if you are using a specular map, it only works if you use the pixel specular checkbox in case you don't want to use a specular map.
But the pixel specular feature is very rarely used since it is not a nice solution.
I also have the suspicion that those sliders and values now work very different than before.

http://duion.com/files/temp/3.9_specularbroken.png

The first slider which goes from 1-128 was first that 1 meant highest specularity and 128 lowest, now it seems to be the other way around, but only if you don't use a specular map as stated before, if using a texture it does not work at all.

**Comment by RichardsGameStudio** [comment]
They will not work with defered shading! Look at the generated shader code:

`   // Deferred Shading: Specular Map
   OUT.col2.g = 1.0;
   float4 specColor = specularMapTex.Sample(specularMap, IN.texCoord);
   OUT.col2.b = dot(specColor.rgb, float3(0.3, 0.59, 0.11));
   OUT.col2.a = specColor.a;
   
   // Deferred Shading: Mat Info Flags
   OUT.col2.r = matInfoFlags;
`
If you would like to work as before, you have to change the code in lighting\advanced\hlsl\deferredShadingFeaturesHLSL.cpp method: void DeferredSpecMapHLSL::processPix( Vector<ShaderComponent*> &componentList, const MaterialFeatureData &fd )

**Comment by Duion** [comment]
It may be good to not have that slider to encourage people to make proper specular maps in the right intensity to begin with.
Alternatively make a new standardized specular map always at full intensity spectrum and always use the slider to adjust it until it fits your needs.
But I don't know how much of that workflow will change with PBR, so I will wait.
