### ISSUE TITLE
"Rotation" instead of "rotation"

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1702]
As I saved a previous mission with the 3.9 build I noticed in my version control that in the mission file every "rotation" was changed into "Rotation" but it should be "rotation" since all other settings are starting with small letters as well.
I could not find where this is done, but this should be undone.

**Comment by Duion** [comment]
https://github.com/GarageGames/Torque3D/pull/1716

**Comment by Areloch** [comment]
#1716 was merged in.
