### ISSUE TITLE
Shadow lags behind with sun object

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1707]
When I use the basic sun object instead of scattersky, which I have to do in a level where I use a skybox, then the shadow of my player extremely lags behind, it feels like the game is just running at 5 fps according to the shadow, but the rest runs fine.

**Comment by John3** [comment]
If i'm not wrong, from inspector panel, you need to change the shadow refresh

**Comment by Duion** [comment]
Related:  http://forums.torque3d.org/viewtopic.php?f=9&t=387
Yes I know now where it comes from, I just wondered why scatterSky is smooth while sun is laggy.

**Comment by Duion** [comment]
It seems to be just an issue with the default settings the objects start out with, so you want me to close this issue?

**Comment by Duion** [comment]
I found another issue related to that, now I have setup static and dynamic shadow objects, when I change the refresh rate from the static objects it works, but when I change the refresh rate of the dynamic objects it always stays smooth, no matter how high the value is I enter there.
So it seems like you cannot adjust the refresh rate of dynamic objects.

**Comment by Azaezel** [comment]
https://github.com/GarageGames/Torque3D/pull/1640 had to shut that end off till we sorted out why it was causing translucent materials to flicker.

**Comment by Areloch** [comment]
It may be worth it to just hide the field in the meantime from appearing in the inspector, since it is currently disabled functionality.

Just to avoid confusion.

**Comment by Azaezel** [comment]
fair enough.

**Comment by Duion** [comment]
I get the idea of having the shadows update less often to save performance, but I'm still trying to find good numbers, the default 250ms are too much, I use 128ms, so roughly half, but you can still see the shadows popping, if you move your mouse fast. For optimal results for fast paced gameplay you will probably have to go below 100ms.
