### ISSUE TITLE
LOD detail levels wrong

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1722]
It looks like the LODing is much stronger since version 3.9 it is at least double that agressive, maybe even 4 times.
I had setup all my models so the LOD popping is hardly visible far in the distance, now I constantly see models popping right infront of me, if I set the settings to lowest there is even whole forests disappearing  right infront of me.
So there must be something seriously wrong with that. Maybe the pixel distance to determine how big the objects are is wrong or the detail adjust rate from $pref::TS::detailAdjust

**Comment by Areloch** [comment]
As I recall it, it was more about making the LOD transitions consistent and reliable in when they occured, as the old logic wasn't quite right, especially at certain aspect changes.

So it could very well be that the default assets need to have updates to their LOD numbers, the transition kickoff should be more correct now than before.

If you've got a video of any behavior you think is erroneous, that could help figure out if there's a bug, or just that assets need updating.

**Comment by Duion** [comment]
Consistent in what way?
Saying that everyone has to update all their models now is a bit bold, especially not knowing what has been changed exactly and that it may be wrong as well, so one would update like 60 models by hand like I have all in Vain then.
I know that it is probably wrong, since I have a nulldetail level at last or am using the "$pref::smallestVisiblePixelSize" for it and they obviously pop out much sooner, with low mesh settings disappearing right in front of your face.
I tested an object with normal settings which is smallestVisiblePixel = 4 in my case and the shape disappears after it is lower than 8 pixel in height and lower than 16-20 pixel diagonal, so it is approximately 4-5 times stronger than it should be.
So am I supposed to use 0.5, 0.25 (which is impossible since 1 pixel is the smallest) values now for smallestVisiblePixel to make up for that miscalculation?
I tested it by zooming out seeing where it disappears, making a screenshot and then counting the pixels the object is big right before it disappears, then you get the size at which it disappears.

**Comment by Duion** [comment]
I made some tests with screenshots showing the difference between 3.8 and 3.9:

http://duion.com/files/temp/3.8lod.jpg
http://duion.com/files/temp/3.9lod.jpg

As you can see 3.9 LODs far earlier then the 3.8

The rock has detail levels 200, 80 and 4 and the 3.8 version properly LODs at 200 pixels from the 200 detail level to the 80 detail level while the 3.9 version seems to LOD from the 200 detail level at when it is 80 pixel big, so maybe someone confused the values there or skipped a LOD level.

**Comment by Duion** [comment]
I did measure the size of the model in the screenshots when it switched from the 200 pixel detail level to the 80 pixel detail level and in the 3.8 version it is 40 pixel and in the 3.9 version it is 130 pixel, so both are wrong, it should be 200 pixels where it switches away from the 200 pixel detail level to the 80 pixel detail level.

**Comment by Duion** [comment]
More values with detailAdjust 1 and with the default soldier:
3.8: It switches from the 300 detail level to 200 detail level at approximately 150 pixels diagonale
3.9: It switches from the 300 detail level to 200 detail level at approximately 450 pixels diagonale

**Comment by RichardsGameStudio** [comment]
In tsShapeInstance.cpp around line 597 the LOD is calculated.

`const F32 pixelScale = (state->getViewport().extent.x / state->getViewport().extent.y);`

if you change this line to

`const F32 pixelScale = (state->getViewport().extent.x / 300.0f);`

you will have the old LODding.

**Comment by Duion** [comment]
Good to know, currently I use:
`const F32 pixelScale = (state->getViewport().extent.x / state->getViewport().extent.y)*2;`
Looks quite crazy to just add a magic number, but from my tests it is pretty accurate in most cases.

**Comment by Areloch** [comment]
#1750 merged in, which uses the *2 quickfix. 

For 4.0, we'll move to a more proper screen-space value for controlling it, but that's a separate thing. For now, this brings the behavior back in line with 3.8.
