### ISSUE TITLE
Ugly fog banding

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1724]
When the fog is a bit heavier and  the fog offset relatively close to the player you can see quite strong ugly banding effects where the fog is not smooth close to the player:
http://duion.com/files/temp/screenshot_TG_Fields_rain007-00001.png

**Comment by Duion** [comment]
Seems to be caused by HDR, it does not happen, if you start the engine with HDR turned off.

**Comment by Areloch** [comment]
The improvements to the fog and hdr formatting largely have resolved this, so I'll close this for now.
