### ISSUE TITLE
Terrain materials are double sided

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1727]
I noticed when I fly under the terrain, it is still visible, this means the terrain materials are all double sided and this cannot be changed, since terrain materials, do not have the value to change if they are double sided or not.
Since double sided materials cost more to render, the terrain should not be double sided.
I also checked one version before and the terrain materials were all single sided like it should be, so they got broken in 3.9 update.

**Comment by Azaezel** [comment]
http://imgur.com/a/87cJt gonna need to do more hunting on this one before we can simply shut culling back off I'm afraid.

**Comment by Areloch** [comment]
Handled with #1838
