### ISSUE TITLE
Strange terrain banding

### ISSUE THREAD

**Issue by RichardsGameStudio** [GarageGames/Torque3D#1740]
Release 3.9:
I've noticed strange terrain banding. It seems that the banding disappears after removing the normal map of the terrainmaterial. It occurs both DX9 and DX11.

See video [here](https://youtu.be/EpLcMkk8RWg)

**Comment by RichardsGameStudio** [comment]
It seems that the banding appears when there are 3 or more terrain layers or 2 layers when there are terrainmaterials with parallax mapping.

**Comment by Duion** [comment]
I already reported that issue a while ago: https://github.com/GarageGames/Torque3D/issues/1701
It is not related to terrain, it also happens on shapes since the normal maps are broken somehow.

**Comment by RichardsGameStudio** [comment]
I don't see this effect on other shapes then the terrain.

**Comment by Duion** [comment]
I have it on my paintball barriers, you can try them out: https://github.com/Duion/Uebergame/tree/master/art/shapes/barriers/inflatable/inflatable_barriers_01

**Comment by RichardsGameStudio** [comment]
I will give this one a try and see what happens.

**Comment by RichardsGameStudio** [comment]
Yes, you are right. Got the same issue on other shapes too.

**Comment by Duion** [comment]
So it is not a terrain issue, but it is the normal maps.

**Comment by RichardsGameStudio** [comment]
Toying around with the generated shaders  GBuffer Conditioner part (see below)

>    // GBuffer Conditioner
>    float4 normal_depth = float4(normalize(gbNormal), eyeSpaceDepth);
> 
>    // output buffer format: GFXFormatR16G16B16A16F
>    // g-buffer conditioner: float4(normal.X, normal.Y, depth Hi, depth Lo)
>    float4 _gbConditionedOutput = float4(sqrt(half(2.0/(1.0 - normal_depth.y))) * half2(normal_depth.xz), 0.0, normal_depth.a);
> 
>    // Encode depth into hi/lo
>    float2 _tempDepth = frac(normal_depth.a * float2(1.0, 65535.0));
>    _gbConditionedOutput.zw = _tempDepth.xy - _tempDepth.yy * float2(1.0/65535.0, 0.0);
>    OUT.col = _gbConditionedOutput;

It seems that modifying the _gbConditionedOutput.zw values to say (0.0,1.0), eliminates this banding effect. Unfortunately, it introduces out of scale PSSM shadows for that terrainmaterial.

**Comment by RichardsGameStudio** [comment]
Fixed by PR #1774
