### ISSUE TITLE
CubeMapShadows not working correctly.

### ISSUE THREAD

**Issue by RichardsGameStudio** [GarageGames/Torque3D#1741]
Release 3.9:
In DX9 dynamic CubeMapShadows missing.
In DX11 CubeMapShadows not working at all.

**Comment by Duion** [comment]
I think they never worked correctly, they being missing might be a new, but it does not really help much since they were not usable before as well.

**Comment by RichardsGameStudio** [comment]
Almost all my shadowmaps are cubemaps and they work perfectly well at least in DX9. Also the dynamic type is easy to add btw.

**Comment by Duion** [comment]
Maybe it has been fixed inbetween, it was quite a long time ago when I tested them.

**Comment by Areloch** [comment]
Hey Rich, sorry for the delay on responding to this.

When you say 'not working at all' can you clarify? Are you getting no shadows? Can't even spawn the light?

When I'm testing, I get artifacting, which I've started looking into, but the light and shadows at least appear in DX11 mode.

**Comment by RichardsGameStudio** [comment]
No problem Areloch, it's a little bit difficult to explain so I have made a vid, showing this scene (which is DX9) with DX11.
![screenshot_001-00001](https://cloud.githubusercontent.com/assets/4663567/18509975/e85b3ad0-7a7b-11e6-9da5-f484d810d5a6.png)

The video[ is here](https://youtu.be/pqb-Zkkx8VU)
The on/off switching of the shadow (dualparaboloid) is another thing which also occurs with DX9 with cubemapshadows (I think this might be a culling issue). I switched of the ScatterSky so all gets dark. Now moving around the pointlight (the selected light in the image) you can see that there is some kind of shadow, but it seems to be completely wrong. My guess is that there is some issue with the viewing direction/frustum or so...

**Comment by RichardsGameStudio** [comment]
Sorry, my fault, old shader was called, problem does NOT exists, so closing issue.
