### ISSUE TITLE
Accumulation textures like (early) Sahara

### ISSUE THREAD

**Issue by RichardsGameStudio** [GarageGames/Torque3D#1744]
As I have models with 2 textures both having a different accumulation texture, it would be nice if the accumulation feature can be applied like (early) Sahara: through the material editor. Accumulation volumes only applies an accumulation on a per object base (afaik), which does not work in the case mentioned.

**Comment by Azaezel** [comment]
Should note there's also https://github.com/GarageGames/Torque3D/pull/1642

**Comment by RichardsGameStudio** [comment]
Yes, I saw that one, but #1642 adds accumulation to a whole level. What I want to do is add an accumulation texture to a material. I have tried changing all the accumulation stuff in 3.9 into my old Sahara version, but that didn't work. I guess because of the changes in the rendering system.

**Comment by Azaezel** [comment]
Hrm... Simplest method would likely be along the lines of fallbacks, similar to the long term work https://github.com/Azaezel/Torque3D/blob/PBR/Engine/source/T3D/tsStatic.cpp#L631-L639 + https://github.com/GarageGames/Torque3D/blob/5d38357785fe999c6263d2ddae758bf3b0ecf0d8/Engine/source/materials/processedMaterial.cpp#L472 that'd allow for the full range of fallbacks, from levels, to volumes to mats. Take a bit of wrenching, so can't really project an eta with the current workload there if nobody else gets to it first...

**Comment by RichardsGameStudio** [comment]
I'm working on it, because it is some kind of a show-stopper for me. I like both methods, so I want to look if it could work together. Problem is that I never digged deep into the material and rendering system, but I will see what I can do.

**Comment by RichardsGameStudio** [comment]
I have the old way working, but the sad news is that you can't use the accumulation volumes to apply accumulation now. As my goal was to get accumulation work through materials, which I have achieved, I will close this issue.
