### ISSUE TITLE
GuiPlatformGenericMenuBar

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1745]
`tools/gui/guiPlatformGenericMenubar.ed.gui (0): Unable to instantiate non-conobject class GuiPlatformGenericMenuBar.`
This is an error message in the console that is there for quite some time now.
I don't really know what it is good for, or if it is used at all, so maybe someone here knows more.
In script it does not seem to be used, but in the source code it appears a few times in those files here:
https://github.com/GarageGames/Torque3D/tree/development/Engine/source/platformSDL/menus

**Comment by Duion** [comment]
So it turned out that you need to activate the checkbox for TORQUE_SDL for the stuff to work, otherwise Torque will use the native Menu bar and it will give you the error message in console, but it will be gone if you compile with SDL.
But if you compile with SDL there is other issues...

**Comment by Areloch** [comment]
Fixed with #1821
