### ISSUE TITLE
SDL2 app icon missing

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1746]
After compiling the engine with the flag "TORQUE_SDL" so that it uses the new SDL2 I noticed that the app icon in the upper left of the window is missing and it shows a default icon instead, but otherwise the icon shows fine, like next to the executable or in desktop shortcuts.

**Comment by wshearn** [comment]
I have found a solution(tested on Linux but should work on Windows).

Follow the image export here and save it as My Projects/<Project>/source/icon.h: https://caedesnotes.wordpress.com/2015/04/13/how-to-integrate-your-sdl2-window-icon-or-any-image-into-your-executable/

When exporting I kept the name gimp_image.

Apply the following

``` diff
index b1d3d04..1d244b6 100644
--- a/Engine/source/windowManager/sdl/sdlWindowMgr.cpp
+++ b/Engine/source/windowManager/sdl/sdlWindowMgr.cpp
@@ -26,6 +26,9 @@
 #include "core/strings/unicode.h"
 
 #include "SDL.h"
+#if TORQUE_SDL_ICON
+#include "icon.h"
+#endif
 
 // ------------------------------------------------------------------------
 
@@ -163,6 +166,28 @@ PlatformWindow *PlatformWindowManagerSDL::createWindow(GFXDevice *device, const
    window->mOwningManager = this;
    mWindowMap[ window->mWindowId ] = window;
 
+#if TORQUE_SDL_ICON
+   Uint32 rmask, gmask, bmask, amask;
+#if SDL_BYTEORDER == SDL_BIG_ENDIAN
+   int shift = (gimp_image.bytes_per_pixel == 3) ? 8 : 0;
+   rmask = 0xff000000 >> shift;
+   gmask = 0x00ff0000 >> shift;
+   bmask = 0x0000ff00 >> shift;
+   amask = 0x000000ff >> shift;
+#else // little endian, like x86
+   rmask = 0x000000ff;
+   gmask = 0x0000ff00;
+   bmask = 0x00ff0000;
+   amask = (gimp_image.bytes_per_pixel == 3) ? 0 : 0xff000000;
+#endif
+
+   SDL_Surface* icon = SDL_CreateRGBSurfaceFrom((void*)gimp_image.pixel_data, gimp_image.width,
+   gimp_image.height, gimp_image.bytes_per_pixel*8, gimp_image.bytes_per_pixel*gimp_image.width,
+   rmask, gmask, bmask, amask);
+   SDL_SetWindowIcon(window->mWindowHandle, icon);
+   SDL_FreeSurface(icon);
+#endif //TORQUE_SDL_ICON
+
    if(device)
    {
       window->mDevice = device;
```

And then in My Projects/<Project>/source/torqueConfig.h add this:
``` #define TORQUE_SDL_ICON true ```

And this is the final result: ![taskbar_torque3d](https://cloud.githubusercontent.com/assets/1176094/20244534/91b97374-a954-11e6-8250-51de17379d61.png)

**Comment by Duion** [comment]
@wshearn I could not manage to integrate your solution for testing, but the app icon in the task bar and in the file browser works for me, just not the one in the upper left corner of the app window, but I already described that in the initial issue, so I'm not sure if your thing is a solution to that.

**Comment by Duion** [comment]
Here is a screenshot where you can see in the upper left corner of the window the missing app icon
http://duion.com/files/temp/brokenskinpreview_normal.jpg
It shows a default icon, normally it is an "ü" as icon.

**Comment by Areloch** [comment]
For the fixing PR, #1878, i went with an image lookup, rather than an embed, as per suggested by @wshearn 
It was a good suggestion, and is actually how the win32 method is, but while it's easy to embed resources in Visual Studio, it's usually a lot less straightforward to do in other IDEs.

So while we aren't going to go with the integrated, your suggestion definitely helped with the PR i ended up making, so huge thanks for your suggestion @wshearn !
