### ISSUE TITLE
SDL2 splash.bmp screen not working

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1747]
After compiling the engine with the flag "TORQUE_SDL" to use the new SDL2 I noticed that the splash window no longer works, the one that displays the splash.bmp bitmap for better app responsiveness.
Instead the window flickers around 2 seconds after the app launch and closes again and after 4-5 seconds the app is fully loaded.
This is the function I'm talking about:
https://github.com/GarageGames/Torque3D/blob/development/Templates/Full/game/main.cs#L99

**Comment by John3** [comment]
please share what is your last commit in testing this build, and for you other issue reported. thx duion

**Comment by Duion** [comment]
What exactly do you want to know?
I merged the 3.9 release into my game, that is what I use for testing mostly, but I also checked with a 3.9 stock Torque3D template for confirming the issue is there as well.
Important for this issue is, that you compile with SDL which causes this issue.

**Comment by Areloch** [comment]
Fixed this via #1755
