### ISSUE TITLE
readme in Torque3D-3.9-LinBinaries.tar.gz has links to non-existance wiki

### ISSUE THREAD

**Issue by cyian-1756** [GarageGames/Torque3D#1753]
The readme in Torque3D-3.9-LinBinaries.tar.gz https://github.com/GarageGames/Torque3D/wiki/Project-Manager to read about/download the project manager and that wiki no longer exists

**Comment by John3** [comment]
What readme? The Torque3D-3.9-LinBinaries.tar.gz file don't have readme.
