### ISSUE TITLE
Using x64 effectively 'disables' use of intrinsic functions.

### ISSUE THREAD

**Issue by Bloodknight** [GarageGames/Torque3D#1757]
example :- 
https://github.com/GarageGames/Torque3D/blob/development/Engine/source/ts/arch/tsMeshIntrinsics.sse.cpp#L24

There's a few other places where intrinsic functions are disabled, and some are in libraries; It appears to be an oversight in the process of making the x64 version work.

**Comment by Bloodknight** [comment]
#1761

**Comment by Areloch** [comment]
Merged #1761

If we find any more, we can just re-open this.
