### ISSUE TITLE
Editor Toggle hide children broken

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1759]
Since version 3.9 the editor options on a SimGroup "Toggle Hide Children" and "Toggle Lock Children" no longer work, nothing happens. Previously in 3.8 it worked and it proberly hid all children objects in the SimGroup.

**Comment by Areloch** [comment]
Figured this one out, will have a PR to fix it up tonight. Thanks for the spot on this!

**Comment by Areloch** [comment]
Please give #1769 a shot, it should fix both the hide and lock toggles for you.

**Comment by Duion** [comment]
Worked for me.

**Comment by Areloch** [comment]
Merged #1769
