### ISSUE TITLE
The gui is can not play effects

### ISSUE THREAD

**Issue by huhorler** [GarageGames/Torque3D#1791]
I want to play effects on the Gui to made the gui beautifull.Is there has any program

**Comment by John3** [comment]
you can use https://github.com/StefanLundmark/Torque3D_Awesomium you embed HTML5/Flash in your games

**Comment by John3** [comment]
BTW you can use the forum to ask this kind of questions. http://forums.torque3d.org/

**Comment by Areloch** [comment]
Yeah, for inquiries on tools and techniques for what you can do, the forum is going to be the better avenue. This area is for noting issues and suggestions for improvements.

I'll go ahead and close this ticket, but by all means, go ahead and make a thread on the forums for more information like what John posted about awesomium.

**Comment by huhorler** [comment]
@John3 I regist an account ,but I can't ask questions.

**Comment by huhorler** [comment]
@Areloch thanks,This is my game problems, different computer game player is not the same, some very Carlton

**Comment by huhorler** [comment]
@John3 thank u,I will ask the questions on the forum then.
