### ISSUE TITLE
sdlPlatformGL.cpp fails when OpenGL is not added in CMake

### ISSUE THREAD

**Issue by lukaspj** [GarageGames/Torque3D#1825]
Hey guys,

I just tried compiling the engine with SDL and DX11 turned on. When I tried to compile it, I got an error in sdlPlatformGL.cpp, where it tries to call the following function: `epoxy_handle_external_wglMakeCurrent` which is undefined.
If I also enable OpenGL, then it works.

So, is this an issue or is SDL dependent on OpenGL?

**Comment by lukaspj** [comment]
Ah, I can see that this might have been addressed already by :
https://github.com/GarageGames/Torque3D/pull/1766

**Comment by JeffProgrammer** [comment]
yeah glad is being used instead of epoxy.

**Comment by lukaspj** [comment]
Yup,  closing
