### ISSUE TITLE
Navmesh flickering in editor in OpenGL

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1860]
In 3.10 when you open a level with a navmesh in the editor it has graphic glitches:
http://duion.com/files/temp/navmeshglitches.jpg
This may be related:
https://gist.github.com/Duion/4467b8db6b3c32bc4ef04d5fee1d2b8d

But try it yourself to confirm it, you just need a navmesh in the level and render mode OpenGL

**Comment by Areloch** [comment]
I'm not experiencing this at all on my end.

**Comment by Duion** [comment]
I recently had a guy with the same bug on Linux, I told him to disable navmesh rendering.
May this have been fixed in the meantime? I'm running the first 3.10 release canditate version.
