### ISSUE TITLE
OpenGL level preview image loading problems

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1861]
This is more related to my game, since I have a preview image in the loading screen from the level, but when I switch to OpenGL render mode, it sometimes does not load or flickers:
http://duion.com/files/temp/brokenloadingscreen.jpg
It is a GuiBitmapCtrl.
And it is set through a script function:
LOAD_MapPic.setBitmap( "levels/load_mission.jpg" );
It only sometimes does not load, for example when first starting the mission.
This issue seems to be there since version 3.10

**Comment by JeffProgrammer** [comment]
oh it's been there way longer than that. since luis added the initial implementation.

**Comment by Duion** [comment]
I may have overlooked it, but I have that loading screen longer and I already tested my game in OpenGL and did not notice it.
