### ISSUE TITLE
Extreme lag spikes in OpenGL when zooming

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1865]
In 3.10 when I have OpenGL on and press zoom I get extreme FPS drop like to 10 FPS from 60 FPS.
This only happens sometimes.
I think it happens when you are in a level and change the shader quality levels (parallax/normal mapping) while in game, then you will get the lags, but not when you first join a level.
This is the console error that comes when that happens:

GFXGLShader::init - Error linking shader!
Program shadergen:/d552ece632483f1a_V.glsl / shadergen:/d552ece632483f1a_P.glsl: Vertex shader(s) failed to link, fragment shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: error(#275) Symbol "_TEXCOORD2_" is defined with 2 different types between two stages
WARNING: warning(#276) Symbol "_TEXCOORD5_" usage doesn't match between two stages
WARNING: warning(#276) Symbol "_TEXCOORD6_" usage doesn't match between two stages
WARNING: warning(#276) Symbol "_TEXCOORD3_" usage doesn't match between two stages
fragment link error: INVALID_OPERATION.
ERROR: error(#275) Symbol "_TEXCOORD2_" is defined with 2 different types between two stages
WARNING: warning(#276) Symbol "_TEXCOORD5_" usage doesn't match between two stages
WARNING: warning(#276) Symbol "_TEXCOORD6_" usage doesn't match between two stages
WARNING: warning(#276) Symbol "_TEXCOORD3_" usage doesn't match between two stages

TerrainCellMaterial::init - Failed to create pass!

And after that:

GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.
GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.

But I already posted that here:
https://github.com/GarageGames/Torque3D/issues/1863
 it also happens at the beginning of loading a level.

**Comment by rextimmy** [comment]
@Duion could you post the contents of d552ece632483f1a_V.glsl & d552ece632483f1a_P.glsl to pastebin or a similar site so i take take a look.

**Comment by Duion** [comment]
https://gist.github.com/Duion/125c2bd0131bb2c5496a24d4f06b405d & https://gist.github.com/Duion/32c4f134d511593ddaae0dbfd37cd64a
