### ISSUE TITLE
[9.10 rc1] lan broke

### ISSUE THREAD

**Issue by Azaezel** [GarageGames/Torque3D#1867]
Looks like networking took a wrong turn at Albuquerque on the LAN end.
http://i.imgur.com/YN4eTIT.jpg

https://gist.github.com/Azaezel/3ded2a4affaca1586c99a57b5e6b99a1

**Comment by Duion** [comment]
I have a problem now that I cannot connect to my own games and the master server is also not available when I open two instances of the game on my computer.
May this be related?

**Comment by Azaezel** [comment]
Sounds similar, yes. was resolved by https://github.com/GarageGames/Torque3D/commit/78993a85dd38324f34ebc6561ba4f2b4ab3ad804 (post RC1)
