### ISSUE TITLE
Canvas picked color does not match on some rgb values

### ISSUE THREAD

**Issue by rasteron** [GarageGames/Torque3D#1870]
Hi, I have noticed this when changing Canvas color values. When using basic color rbg combination like magenta it matches ok..

**#ff00ff**
![canvas2](https://cloud.githubusercontent.com/assets/3676827/21267214/618fbc1c-c3e4-11e6-91c0-da9973932f34.png)

but when tested on some gradient combination particularly gray here, the result is a much lighter color and completely off:

**#202020**
![canvas1](https://cloud.githubusercontent.com/assets/3676827/21267218/646e5dee-c3e4-11e6-9e8b-f3b708f10efd.png)

**Comment by rextimmy** [comment]
It's the difference in the color space, It should be fixed up soon, most likely a tickbox so you can toggle sRGB preview on/off.

**Comment by rasteron** [comment]
Thanks guys! closing now.
