### ISSUE TITLE
Improve default flags for cmake

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1872]
When you generate a new project with cmake the default settings could be improved by activating:
TORQUE_D3D11
TORQUE_OPENGL
TORQUE_SDL
by default as well, since most people will want to have those features in the game, otherwise the default settings cmake generates are pretty  good already and with those settings additionally there would be almost no need to adjust the flags anymore, except for special needs like dedicated builds etc.

**Comment by JeffProgrammer** [comment]
#1858 ?

**Comment by Duion** [comment]
Oh sry did not see that there is already a pull request for it.
