### ISSUE TITLE
After resaving EditorGui.gui for example, engine crashes on startup

### ISSUE THREAD

**Issue by hsdxpro** [GarageGames/Torque3D#1873]
development & master branch, 32bit windows, DirectX9, no SDL, build.

Reproduce with this:
1. Open GUI Editor
2. Open EditorGui.gui
3. Save as.. overwrite the existing file
4. Close editor
5. Open editor (here crash should occur)
6. Open EditorGui.gui (here 100% crash will occur)

**Comment by Azaezel** [comment]
That'll happen due to the combination of procedurally generated guis, saving the results of them, and the system trying to tack on duplicates as it's procedurally re-created, unfortunately.

**Comment by JeffProgrammer** [comment]
Yup, for editing the editor itself I always code it by hand. Just easier.

**Comment by hsdxpro** [comment]
Thanks guys, it makes sense !

In addition to what I wrote, I found another unwanted behavior.

This is the content of one GuiControl inside guiMaterialPropertiesWindow.ed.gui :
- as you can see there is no "gridBitmap" field

```
new GuiSwatchButtonCtrl() {
                           canSaveDynamicFields = "0";
                           internalName = "colorTintSwatch";
                           Enabled = "1";
                           isContainer = "0";
                           Profile = "GuiInspectorSwatchButtonProfile";
                           HorizSizing = "right";
                           VertSizing = "bottom";
                           position = "55 33";
                           Extent = "16 16";
                           MinExtent = "8 2";
                           canSave = "1";
                           Visible = "1";
                           Command = "getColorF(materialEd_PreviewMaterial.diffuseColor[MaterialEditorGui.currentLayer], \"MaterialEditorGui.updateColorMultiply\");";
                           hovertime = "1000";
                           groupNum = "-1";
                           buttonType = "PushButton";
                           useMouseEvents = "0";
                        };
```

After opening this gui file in the editor, and selecting this GuiSwatchButtonControl, the 
gridBitmap field will be filled with "U#%" or with something garbage, thus saving this, will store the garbage as well, and reopening it later will crash the engine, because "U#%" is not a correct path to a bitmap file

**Comment by hsdxpro** [comment]
Good news, I fixed the issue locally, I will make a pull request about it :)
