### ISSUE TITLE
Game not launching correctly

### ISSUE THREAD

**Issue by HowBoutSomeSnus** [GarageGames/Torque3D#1884]
http://pastebin.com/WzBHWUR6

^

Game window opens, but blank
This issue occurred in Uebergame, with the latest release of the engine.
Developer assured me it was an engine problem

**Comment by Duion** [comment]
Yes, we tested it with the last versions binary and it launched so the issue is not in the games scripts.
So it happened somewhere in 3.9 or 3.10 in the engines source code. There is a slight possibility that it came from my additions, but I don't think so.
Best thing would be, if someone who has this issue can run it through a debugger, since the console output does not show the issue.

**Comment by HowBoutSomeSnus** [comment]
I can of course run it through a debugger, if you tell me how.

**Comment by Areloch** [comment]
Sorry for the delay on responding to this.

If you're still encountering the issue, do you have just the console.log file? It looks like the linked pastebin is a stacktrace or something more in-depth. Just the regular console.log would better narrow down if there's any particular errors the script is reporting without needing to wade through the stack just yet.

**Comment by HowBoutSomeSnus** [comment]
Surely, here it is attached.
If I run through the terminal, it also says "Engine initialized" before 
it crashes,
which isn't stated in the console.log file.

**Comment by John3** [comment]
@HowBoutSomeSnus you still have this issue?

**Comment by HowBoutSomeSnus** [comment]
@John3 Thanks for your interest.
I would'nt know since now it doesn't launch at all. I just tried to run the engine itself with latest binary from Torques website (3.10), and I got:

`symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`

as output in the terminal.

**Comment by HowBoutSomeSnus** [comment]
Hi, sorry for late reply.
In version Uebergame version 1.1.0.0, just released, there are no problems whatsoever :)

**Comment by Areloch** [comment]
Cool, good to hear. Dunno what the cause ended up being, but if it's resolved, then that's good :)
