### ISSUE TITLE
PosixFileSystem::rename infinitely recurses

### ISSUE THREAD

**Issue by elfprince13** [GarageGames/Torque3D#1913]
Clang warns that "all paths through this function will call itself".
```
bool PosixFileSystem::rename(const Path& from,const Path& to)
{
   String fa = buildFileName(_volume,from);
   String fb = buildFileName(_volume,to);
   
   if (!rename(fa.c_str(),fb.c_str()))
      return true;
      
   return false;
}

```
I can't find any definition of `rename` in scope (or anywhere in the project) that takes `const char *`, so I suspect there is an implicit conversion back to `const Path&` taking place. Does anybody know which `rename` was originally supposed to be called here?

**Comment by elfprince13** [comment]
Just wanted to bump this - does anybody know what's supposed to be happening here?

**Comment by dottools** [comment]
Sounds like it's suppose to call [`::rename()`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/rename.html).

**Comment by elfprince13** [comment]
Aha, I believe you're correct.
