### ISSUE TITLE
[Bug] World Editor Screen and GUI goes black.

### ISSUE THREAD

**Issue by HeadClot** [GarageGames/Torque3D#1918]
Reproduction for this bug - 
1. Open up the level editor from the main menu.
2. After the World editor fully loads click on the GUI editor button.
3. Click back on the World Editor button to go back to the World editor.
4. World Editor and UI should be black. Example -> http://i.imgur.com/LzF1GGh.png

Version of T3D: 3.10 RC2

System Specs - 

CPU: AMD 6100 FX 3.0 GHz
GPU: AMD R7 265 2GB
Ram: 16GB

If you need more info please let me know.

**Comment by John3** [comment]
You still have this issue? Are you using the T3D SDL version?

**Comment by Areloch** [comment]
I was able to replicate this(to be specific, it's not simply 'black' but 'canvas color'.

I'm looking into a fix for this.

**Comment by HeadClot** [comment]
Hey Areloch anad John3 thanks for the replies.

Areloch - Glad you were able to repro this issue. If you find a fix let me
know. :)

John3 - I am unsure. I just used the latest binaries.

**Comment by Areloch** [comment]
Can you try #1933 and see if it resolves this for you?

**Comment by HeadClot** [comment]
@Areloch - I am not much of a programmer but I Will give it a shot :)

**Comment by Areloch** [comment]
I went ahead and merged it in as everything seemed to work, so I'll close this for now. If you run into any problems with this still, even with that PR rolled in, feel free to comment here and and we can re-open it :)
