### ISSUE TITLE
Lightning is not rendering 

### ISSUE THREAD

**Issue by petrifiedroadkill** [GarageGames/Torque3D#1927]
Lightning objects do not seem to spawn/render any bolts. I have tired dx9  dx11 and openGl.
This was on the current development build as of this posting.

**Comment by Areloch** [comment]
Hey guys, can you test out #1931 and make sure it fixes everything on your end?

Looks like it was an oversight with the stateblock settings in that if you didn't bind a texture for the lightning strikes, it wouldn't properly fall back to the flat colors.

**Comment by RichardsGameStudio** [comment]
@Areloch: I did it slightly different so you are able to use more than 1 texture. If you are interested I can send the files by e-mail to you.

**Comment by Areloch** [comment]
Yeah, by all means. Feel free to send it to areloch at gmail dotcom.

**Comment by RichardsGameStudio** [comment]
Send the files lightning.cpp and .h and the texture I use.

**Comment by Areloch** [comment]
Awesome!

**Comment by Areloch** [comment]
Seems to work pretty well!

Did you want me to include the texture with the improvements on the PR?

**Comment by RichardsGameStudio** [comment]
If you like, I have no problem with that.

**Comment by petrifiedroadkill** [comment]
I tired the changes, only thing that stands out to me is when you use a texture. The bolt does not fade away, instead it just hangs there for a bit then disappears. Without the texture everything behaves correctly.

**Comment by Areloch** [comment]
Hm, this is true. How would we preferably deal with that? Use the texture slots as animation frames? Do a straight alpha-fade out?

**Comment by petrifiedroadkill** [comment]
Hmm that is a hard one but i think id lean more towards using the texture slots as an animation.

**Comment by RichardsGameStudio** [comment]
Mmm, the lightning is fading here. Strange.

**Comment by petrifiedroadkill** [comment]
This is what i see https://www.youtube.com/watch?v=b6zoApoGMEo

**Comment by RichardsGameStudio** [comment]
My version shows this: [(https://youtu.be/8m1sGUjfYaQ)]

**Comment by Areloch** [comment]
I probably missed a bit from the files you provided(winmerge was not being helpful for whatever reason). I'll take another look at it and see what didn't carry over.

**Comment by Areloch** [comment]
Sure enough, missed a setting with the stateblock description. Corrected and added a little bit of extra cleanup on the code. Give it a whirl to confirm it's all good, if you could :)

**Comment by petrifiedroadkill** [comment]
Everything works :) its good to go.

**Comment by Areloch** [comment]
PR merged in :)
