### ISSUE TITLE
Strange Glitch and enormous use of CPU

### ISSUE THREAD

**Issue by RealAquilus** [GarageGames/Torque3D#1966]
![t3d](https://cloud.githubusercontent.com/assets/20306523/23917541/fc8ff4de-08ef-11e7-97f8-555b49272794.png)
![t3d2](https://cloud.githubusercontent.com/assets/20306523/23917542/fc946d52-08ef-11e7-9a4b-d52361897f3a.png)
I'm new to this i have just started the demo using the precompiled version and i get this strange glitch, and a very high use of CPU (i have an i7 4790k and i start from 40c going to 82c using torque! why?)

**Comment by Azaezel** [comment]
Need more info, like a console log shoved over onto a gist, http://pastebin.com/ , or https://hastebin.com/ say.

**Comment by John3** [comment]
Hi @RealAquilus have you still have the same problem? can you share more info about the issue, like what build you used "Debug" or "Release" and share the console.log. 

@Azaezel we can close this issue if we don't have any feedback.
