### ISSUE TITLE
Visual studio 2017 Template flaws

### ISSUE THREAD

**Issue by Azaezel** [GarageGames/Torque3D#1969]
Seems various things are cropping up of late regarding the handling of templates and the latest VS version. Forum thread: http://forums.torque3d.org/viewtopic.php?f=10&t=979

**Comment by chaigler** [comment]
This was supposed to be fixed in the VS2017 15.3 release but the preview build of 15.3 still has the same issue (multiple C2938 errors showing 'MaybeSelfEnabled<TailTs...>' - Failed to specialize alias template). 

I have no idea how to fix this but it's especially concerning because VS2017 is the only version Microsoft is offering for download.

**Comment by BenNottelling** [comment]
Actually you can still download old versions of visual studio for free here: https://www.visualstudio.com/vs/older-downloads/ 
It's still from Microsoft

**Comment by chaigler** [comment]
@BenNottelling Thanks Ben. I had seen that link before but assumed the part about needing a subscription ("You can download old versions of Visual Studio and other software through a subscription.") meant they were locked behind some paywall. Good to know!

I'd still like to get this fixed but at least we have an alternative for now.

**Comment by BenNottelling** [comment]
@chaigler Welcome!

**Comment by Azaezel** [comment]
https://developercommunity.visualstudio.com/content/problem/25618/visual-studio-2017-template-issues.html generl thinking at this point seems to be giving em a bit longer to clean things up their end before suggesting over-complicating the codebase for a single version issue that should be resolved 'shortly'.

*should

**Comment by rextimmy** [comment]
We have a fix for VS 2017 now, just doing a bit of further testing, should be a PR for it very soon.

**Comment by chaigler** [comment]
@rextimmy Nice! Also: lol @ the struct name.

**Comment by Areloch** [comment]
Fixed via PR.
