### ISSUE TITLE
Edit and continue isn't working in VS2012

### ISSUE THREAD

**Issue by lukaspj** [GarageGames/Torque3D#198]
In visual studio 2012 you can't do edit and continues unfortunately..

I believe it has something to do with the SAFESEH:NO option as explained [her](http://www.garagegames.com/community/forums/viewthread/131675/1#comment-833697)

It's a pretty awesome feature so if anyone have been able to solve this please post your solution :)

I would fix it myself if I had an idea how to.

**Comment by Areloch** [comment]
2012's deprecated. Just forgot to close this ticket out ;)
