### ISSUE TITLE
twin include

### ISSUE THREAD

**Issue by maddin200** [GarageGames/Torque3D#1999]
/Engine/source/console/scriptObjects.cpp) (line 27): 
#include "console/simBase.h"

**Comment by Areloch** [comment]
Good spot!

**Comment by Areloch** [comment]
Quick inquiry: any chance you have the time to do a quick PR for the fix? Hopefully it's not too much trouble, but it'd definitely make it easier :)

**Comment by maddin200** [comment]
better you provide the patch; I'm not familiar with the code.

**Comment by Areloch** [comment]
Heh, fair enough, though I'd say you're always welcome to give it a shot in the future! You spotted the issue well enough, I know you'd be able to correct this sort of thing and submit a PR going forward :)

If you ever feel like giving it a shot and just don't know what to do, feel free to ask :D

**Comment by Areloch** [comment]
Fixed via PR
