### ISSUE TITLE
dumpConsoleClasses() crashes torque

### ISSUE THREAD

**Issue by andijh92** [GarageGames/Torque3D#2005]
dumpConsoleClasses() crashes torque.

i was using: 
ubuntu 16.04.
torque 3.10 (last commit c460868814f1b41c954fdd963ea9a7f60c017f18 )
self compiled binaries and default game template via $ make install

Tail of the output: https://pastebin.com/nuehK2in

dumpConsoleFunctions(), dumpEngineDocs("foo") and playing a little bit the default game template worked.

**Comment by Areloch** [comment]
I've figured out where it crashes, I've mostly been looking through for the 'why' so it can get fixed.

**Comment by Areloch** [comment]
Dunno if you spotted the PR, but if you could eyeball #2008 and see if that fixes the crash on your end, I can get it rolled in.

**Comment by andijh92** [comment]
Sry, for the delay! Now it's tested.

**Comment by Areloch** [comment]
Fixed
