### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by maddin200** [GarageGames/Torque3D#2012]
\Engine\lib\collada\src\dae\daeRawResolver.cpp
line 61
missing 
fclose(rawFile);

**Comment by Alex2324** [comment]
I believe that fclose is called on line 108.

**Comment by rextimmy** [comment]
@Alex2324  , no @maddin200 is correct, fopen is called on line 50, than on line 60 you have that if statement, if that happens to be true than the function returns NULL but never calls fclose.

**Comment by Areloch** [comment]
Wow, nice spot!

**Comment by Areloch** [comment]
Closed per PR. Thanks! :)
