### ISSUE TITLE
Terrain texture colors are off since 3.8

### ISSUE THREAD

**Issue by lukaspj** [GarageGames/Torque3D#2050]
As detailed by @Bloodknight [here](http://forums.torque3d.org/viewtopic.php?f=2&p=8394#p8388), the terrain textures seem slightly off in color. It's more pronounced the more detailed the textures become.
The major issue with this, is that it complicates the use of detail-textures as the close-up color contributor for terrains.

3.8:
![](http://i.imgur.com/qSyXlRX.jpg)

3.9/3.10:
![](http://imgur.com/JyjR7GF.jpg)

**Comment by lukaspj** [comment]
An example of a shader from #2049 can be seen here:
https://gist.github.com/lukaspj/ecd9d46426889c611a565b6edde12572

Not much has changed since 3.8, in terms of computation of color. The major thing would be linearization, which I would believe is the culprit.

My guess would be that grayscale = don't use toLinear, as it is a lighting effect, but color = use toLinear as it is a diffuse texture. Detail textures sort of acts both ways, thus it both should and shouldn't be linearized, and that could throw the math off. That would explain why gray-scales seem unaffected by this issue, as far as I know at least.

**Comment by Areloch** [comment]
Solved via #2051
