### ISSUE TITLE
Shader include path bug in BaseGame template.

### ISSUE THREAD

**Issue by zyzz19951230** [GarageGames/Torque3D#2079]
Today I tried to compile T3D with the BaseGame template, after i hit the “Launch World Editor” button, some errors occurred. Some  dialogs popped with the info "Failed to open the include 'shaders/common/torque.hlsl'". i think this is a path bug, may be the developers forgot to update the include file path in some shader files, casue the "torque.hlsl" is no longer in the "shaders/common" path but in the "shaders/" path in the BaseGame template.

Here is the post in the forum with  screenshots. Hope that  helps .

**Comment by zyzz19951230** [comment]
forgot to paste  the  link http://forums.torque3d.org/viewtopic.php?f=12&t=1080. sorry.

**Comment by zyzz19951230** [comment]
UPDATE: Find some info in the console.log file. And the same problem occurs when i use OpenGL as the render. It turns out my guess may be wrong, the problem is not exist in some shader file but in this "Engine\source\gfx\D3D11\gfxD3D11Shader.cpp" file.

failed to compile shader: C:\Users\Administrator\Documents\GitHub\Torque3D\My Projects\LearnT3DBaseGame\game\data\shaderCache\efef832dc37c8755_V.hlsl(6,10): error X1507: failed to open source file: 'shaders/common/torque.hlsl'
C:\Users\Administrator\Documents\GitHub\Torque3D\Engine\source\gfx\D3D11\gfxD3D11Shader.cpp(950,0): {Fatal-ISV} - Unable to compile shader!
Failed to initialize material '(null)'
C:\Users\Administrator\Documents\GitHub\Torque3D\Engine\source\gfx\D3D11\gfxD3D11Shader.cpp(72,0): {Fatal-ISV} - Failed to open include 'shaders/common/torque.hlsl'.
failed to compile shader: C:\Users\Administrator\Documents\GitHub\Torque3D\My Projects\LearnT3DBaseGame\game\data\shaderCache\a1a7a101cca9ce72_V.hlsl(6,10): error X1507: failed to open source file: 'shaders/common/torque.hlsl'

**Comment by zyzz19951230** [comment]
UPDATE2:

I did little more research, found the problem should be in "Engine\source\shaderGen\shaderGen.cpp". I noticed that in line 52 and line 129, there was a string "shaders/common" and a variable named smCommonShaderPath which should control where should the auto-generated shaders go:

line52: String ShaderGen::smCommonShaderPath("shaders/common");
line129: smCommonShaderPath = String(Con::getVariable("$Core::CommonShaderPath", "shaders/common"));


And the smCommonShaderPath should be able to change from the script, and i found it in game\core\main.cs:
line42: $Core::CommonShaderPath = "core/shaders";

But i just don't konw why this line does not take effect. The game\core\main.cs should be executed. I am confused now.

**Comment by Areloch** [comment]
It should be getting overridden, yes. I'll take a look, because I definitely recall testing it and not having an issue in either case. It could've been I made a tweak and forgot to get it checked in. I'll be taking a look at this and will get it corrected, thanks!

**Comment by John3** [comment]
Hmm 🤔 @Areloch maybe github do not send an email about this comment https://github.com/GarageGames/Torque3D/commit/7567ca10c38e19750c8289c3473a84d16e85af9a#commitcomment-23496668

@zyzz19951230 you can use this temporary fix https://github.com/GarageGames/Torque3D/commit/7567ca10c38e19750c8289c3473a84d16e85af9a#commitcomment-24237118

**Comment by Areloch** [comment]
Hey guys. Try #2080 It should resolve this. It was just an ordering issue that meant that the core shadergen paths were set with the default value before the script-defined path was established.
