### ISSUE TITLE
Typo in afxParticlePool_T3D.cpp

### ISSUE THREAD

**Issue by faculezcano** [GarageGames/Torque3D#2107]
When trying to compile it fails on afxParticlePool_T3D.cpp on linux
It complains for lighting/lightinfo.cpp that is lighting/light**I**nfo.cpp:

https://github.com/GarageGames/Torque3D/blob/d7a8510756270561aea6db5edcd43596d93eec6e/Engine/source/afx/util/afxParticlePool_T3D.cpp#L31

Changing that "i" to "I" fixes the problem

**Comment by Areloch** [comment]
Ah, Lunix case sensitivity strikes again. Good find!

Any chance you could smash out a quick PR for it since you've got the change already? If not, I can :)

**Comment by faculezcano** [comment]
Done! #2113
