### ISSUE TITLE
Crash loading certain PNG files

### ISSUE THREAD

**Issue by nev7n** [GarageGames/Torque3D#2137]
GUIBitmapCtrl trying to load this png:
https://www.dropbox.com/s/iptnkq5e9wzezjw/animationbar_left_end.png?dl=0

Causes crash with this error:
```
 D:\Torque\Torque3D\Engine\source\gfx\bitmap\loaders\bitmapPng.cpp(125,0): {Fatal-ISV} - Error reading PNG file:
IDAT: chunk data is too large
```

Caused by this libpng bug:
https://sourceforge.net/p/libpng/bugs/270/

Should be fixed by libpng 1.6.33 and higher, we worked around the issue by re-saving the PNGs in photoshop  (save for web -> PNG24).

**Comment by JeffProgrammer** [comment]
@Areloch this can probably be closed.

**Comment by nev7n** [comment]
This was resolved by the newer version of libpng
