### ISSUE TITLE
SDL2 still linking dxerr.lib

### ISSUE THREAD

**Issue by chaigler** [GarageGames/Torque3D#2163]
SDL2 is still linking dxerr.lib on Windows. dxerr.lib was deprecated years ago and isn't included in any of the recent Windows SDKs so it breaks compilation unless the DX SDK is installed (gross). SDL2 doesn't actually use this lib so I'm not sure why it links it at all.

Here's some more info: https://github.com/davidsiaw/SDL2/issues/1

Easy fix, just update the SDL2 make file to remove the dependency.

**Comment by Areloch** [comment]
Fixed per PR.

**Comment by chaigler** [comment]
@Areloch - Looks like this creeped in again in one of the recent PRs. We're back to linking against dxerr.
