### ISSUE TITLE
Build fails when compiling without Basic Lighting

### ISSUE THREAD

**Issue by chaigler** [GarageGames/Torque3D#2169]
Compiling without Basic Lighting (TORQUE_BASIC_LIGHTING unchecked in CMake) causes linker errors due to projectedShadow relying on BasicLighting::smProjectedShadowFilterDistance. Also, the engine will assert on exit due to ShadowMapManager being destroyed before AdvancedLightManager.

**Comment by Areloch** [comment]
Fixed per PR.
