### ISSUE TITLE
Openal-soft Broke Linux

### ISSUE THREAD

**Issue by practicing01** [GarageGames/Torque3D#2353]
1) Missing includes when compiling.
2) Crash on application start after successful compile.

**Comment by practicing01** [comment]
This seems to fix it: https://github.com/practicing01/Torque3D/commit/5c5bfdd0a7019f86ed4e8fde64342a3d1621462c

**Comment by Alexmac22347** [comment]
same issue with me, missing openal.h headers, segmentation fault when I get it to compile.
Will try out the fix, thanks for the info!

**Comment by Areloch** [comment]
Merged in #2362
