### ISSUE TITLE
Mapping a material using the material editor leads to bad UVS

### ISSUE THREAD

**Issue by cggart** [GarageGames/Torque3D#276]
![exmaple](https://f.cloud.github.com/assets/3935254/293717/b1d0d21e-93a6-11e2-8e1c-ec4feff09bf3.jpg)
Either select a model in the mission or load one in the shape editor.  Then map a new material and the UVs on that model break (are skewed and distorted).  If the changes are saved and torque is restarted the issue goes away.

**Comment by John3** [comment]
Hi, This is still a bug? :S I loaded different models with UVs of course and I don't remember this happen to me. How can we test this? or it can be closed? @Areloch ???

**Comment by Areloch** [comment]
Thinking this was fixed at some point, and still can't replicate it, so I'm just going to close this.
