### ISSUE TITLE
Material Editor Preview - Ambient Light Color is not used in the preview.

### ISSUE THREAD

**Issue by RaymondMitchell-GG** [GarageGames/Torque3D#357]
In the material editor, changing the ambient light color for the preview does not change the lighting in the preview.

Expected: Ambient light color is used in the preview.

Steps to reproduce:
1. Open the material editor.
2. Change the ambient preview color.
3. Observe the preview lighting does not change.

Note: The Normal Light Color does affect the lighting in the preview, the Ambient Light Color does not affect the lighting in the preview.

**Comment by Areloch** [comment]
Looks like this actually does behave in current builds.
