### ISSUE TITLE
Using LF (\n) instead of CRLF (\r\n) causes some parsing errors.

### ISSUE THREAD

**Issue by lukaspj** [GarageGames/Torque3D#396]
Ran a tool on my code which, among other things, replaced all file endings with LF.
This resulted in a lot of parsing errors in some of the script (not all, just some of them 8 in total)

Example of an error:
```
core/scripts/client/audio.cs Line: 414 - syntax error
>>> Advanced script error report.  Line 414.
>>> Some error context, with ## on sides of error halt:
///                     string to pause sources on all channels.
/// @param %pauseSet    An optional SimSet which is filled with the paused 
///                     sources.  If not specified the global SfxSourceGroup 
///                     is used.
///
/// @deprecated
///
function sfxPause( %channels, %pauseSet )
{
## ##  // Did we get a set to populate?
   if ( !isObject( %pauseSet ) )
	  %pauseSet = SFXPausedSet;
	  
   %count = SFXSourceSet.getCount();
   for ( %i = 0; %i < %count; %i++ )
   {
	  %source = SFXSourceSet.getObject( %i );

	  %channel = sfxGroupToOldChannel( %source.getGroup() );
>>> Error report complete.
```
Complete list of files that gave an error:
* core/scripts/client/audio.cs Line: 414 - syntax error
* tools/editorClasses/scripts/projects/projectEvents.ed.cs Line: 27 - syntax error
* tools/editorClasses/scripts/projects/projectInternalInterface.ed.cs Line: 131 - syntax error
* tools/editorClasses/scripts/input/inputEvents.ed.cs Line: 27 - syntax error
* tools/base/menuBar/menuBuilder.ed.cs Line: 193 - syntax error
* tools/worldEditor/scripts/editors/terrainEditor.ed.cs Line: 36 - syntax error
* tools/worldEditor/scripts/editors/terrainEditor.ed.cs Line: 36 - syntax error
* tools/datablockEditor/datablockEditor.cs Line: 338 - syntax error

Windows8x64 MIT 3.0 with no changes except line endings.

**Comment by JeffProgrammer** [comment]
Looking into this...

**Comment by JeffProgrammer** [comment]
the regular expression requires at least 1 character after the 3 slash marks in order for it to compile from what I see, the regular expression:

[code]("///"[^/][^\n\r]*[\n\r]*)+ { return(Sc_ScanDocBlock()); }[/code]
