### ISSUE TITLE
mesh names in, Scene tree, Library, meshes, error

### ISSUE THREAD

**Issue by deadlyduckuk** [GarageGames/Torque3D#400]
Mesh names in Scene tree, Library, meshes if they have a space in the filename display wrong.

to see this bug, rename any dts or collada with a space in the name, then go to Scene tree, Library, meshes, (wherever its located)

you will see its also in a folder called whatever the name was before the space.

Its caused by the script replacing all "/"'s as spaces, then striping the words out.
It's fixed by replacing any spaces in the filename with a placeholder character then replacing the placeholder with a space as soon as the words have been striped out.

I have posted this as a resource (although its gone into blogs) with this simple fix.
http://www.garagegames.com/community/blogs/view/22295

**Comment by Areloch** [comment]
This got fixed.
