### ISSUE TITLE
Enable DirectX 9Ex 

### ISSUE THREAD

**Issue by thecelloman** [GarageGames/Torque3D#458]
As indicated in the closed Pull Request #443 

   // Comment this in order to disable using Direct3D9Ex feature
   $pref::Video::preferDirect3D9Ex = true;

**Comment by Areloch** [comment]
I don't know that that would really enable any new specific behavior just by flipping it on, and we're going to be removing DX9 in 4.0. 

I'll close this issue unless someone knows if 9ex does anything special just by virtue of activating it.
