### ISSUE TITLE
Deleting GUIContainer does not delete child objects

### ISSUE THREAD

**Issue by Phantom139** [GarageGames/Torque3D#469]
Title describes it perfectly, deleting a GUIContainer does not delete all of it's child objects. Repeating is simple, go into the GUI Editor, create a new GUIContainer add an object to it and assign it a name, delete the container and try to create a new control using the same child object name, get existing object error, complain as you need to open the console to delete it... Rinse, wash, repeat, ect.

**Comment by Areloch** [comment]
Unless there'd be any particular reason that the delete would need to be 'real' during gui editing, I don't think this is really a problem, and keeps the undo system clean and effective.
