### ISSUE TITLE
Custom GUI Profile/Files issue

### ISSUE THREAD

**Issue by rasteron** [GarageGames/Torque3D#479]
Saving and reloading issues with Custom GUI profiles and default .gui files, using ~~consolefuncrefactor branch.~~ development branch (merge happened).

**Comment by eightyeight** [comment]
@rasteron creating and saving a GUI profile as you describe works for me with the fixes from #1165. Can you verify?

**Comment by rasteron** [comment]
hey @eightyeight sorry I'm currently busy with other stuff and have moved on with testing an older build. If this version is now merged and tested then I guess we can close this for now.

thanks.
