### ISSUE TITLE
Cannot create empty ShapeBaseImageData block

### ISSUE THREAD

**Issue by crabmusket** [GarageGames/Torque3D#696]
As noted in [this thread](http://www.garagegames.com/community/forums/viewthread/137051), attempting to create a `ShapeBaseImageData` block results in a failure if no parent block is specified. This needs to be fixed either in the editor, by allowing parameters to be added to the datablock before it is created, or in the engine, by allowing an empty datablock to exist.

**Comment by John3** [comment]
A fix for this default will be add "shapeFile = "core/art/shapes/noshape.dts";" my default.
