### ISSUE TITLE
Fatal error-Shader quality lowest with lighting quality above lowest

### ISSUE THREAD

**Issue by Azaezel** [GarageGames/Torque3D#770]
devhead as of Aug 20, 2014
the posted setting combination triggers 
https://github.com/GarageGames/Torque3D/blob/69838bdc8c9bc055b9b1ae76f42b0f28d2a33909/Engine/source/lighting/advanced/glsl/gBufferConditionerGLSL.cpp#L95
seems to have cropped up after 3.5.0

**Comment by LuisAntonRebollo** [comment]
Fixed on #1238
