### ISSUE TITLE
Linux Mint ( Nvidia GTX 650) engine does not start.

### ISSUE THREAD

**Issue by raftakis** [GarageGames/Torque3D#987]
Hi I download and compile the latest souce, 
Compilation was succesfull, but i was not able to start the engine.
I use Linux Mint winth NVIDIA GTX 650 (NVIDIA drivers 340.58) 

I Folowed the README.md  instructions and steps, and i create a new project "rafman" based on Full.

The output on my system was the bellow:

rafman@hermes ~/Torque3D-development/My Projects/rafman/game $ ./rafman -dedicated -mission "levels/Empty Terrain.mis"

Binding server port to default IP
UDP initialized on port 0
Attempting to create GFX device: GFX Null Device []
Initializing GFXCardProfiler (GFX Null Device Renderer)
   o Chipset : 'NULL Device'
   o Card    : 'GFX Null Device Card'
   o Version : '0'
   o VRAM    : 0 MB
- Scanning card capabilities...
- Loading card profiles...
  - No card profile core/profile/GFXNullDeviceRenderer.cs exists
  - No card profile core/profile/GFXNullDeviceRenderer.NULLDevice.cs exists
  - No card profile core/profile/GFXNullDeviceRenderer.NULLDevice.GFXNullDeviceCard.cs exists
  - No card profile core/profile/GFXNullDeviceRenderer.NULLDevice.GFXNullDeviceCard.0.cs exists
    Device created, setting adapter and enumerating modes
    Format GFXFormatR8G8B8A8 not supported with specified profile.
    Format GFXFormatR8G8B8X8 not supported with specified profile.
    Format GFXFormatR8G8B8A8 not supported with specified profile.
    Format GFXFormatR8G8B8A8 not supported with specified profile.
    Format GFXFormatR8G8B8A8 not supported with specified profile.
    GuiControlProfile::loadFont - Failed to load/create profile font (Arial/14)
    % - PostFX Manager - Executing core/scripts/client/postFx/default.postfxpreset.cs
    % - PostFX Manager - Applying from preset
    % - PostFX Manager - PostFX enabled
    core/scripts/client/core.cs (118): Unable to find object: 'Canvas' attempting to call function 'setCursor'
    % - Initialized Core
    % 
    --------- Initializing Directory: scripts ---------
    sfxStartup...
    SFXSystem::createDevice - created Null device 'SFX Null Device'
    Provider: Null
    Device: SFX Null Device
    Hardware: No
    Buffers: 16
    % 
    --------- Initializing rafman: Server Scripts ---------
    % 
    --------- Starting Dedicated Server ---------
    Exporting server prefs...
    Starting multiplayer mode
    Binding server port to default IP
    UDP initialized on port 28000
    Warning: shape art/shapes/weapons/Turret/Turret_Legs.DAE collision detail 0 (Collision-1) bounds exceed that of shape.
    Warning: shape art/shapes/weapons/Turret/Turret_Legs.DAE collision detail 0 (Collision-1) bounds exceed that of shape.
    Warning: shape art/shapes/weapons/Turret/Turret_Legs.DAE collision detail 0 (Collision-1) bounds exceed that of shape.
    TSShape::removeNode: Node 'collision-1' has 1 objects attached, these will be reassigned to the node's parent ('null')
    TSShape::removeNode: Node 'Cheetah_Turret_LOD300' has 1 objects attached, these will be reassigned to the node's parent ('null')
    TSShape::removeNode: Node 'Tread_LOD300' has 1 objects attached, these will be reassigned to the node's parent ('null')
    TSShape::removeNode: Node 'collision-1' has 1 objects attached, these will be reassigned to the node's parent ('null')
    TSShape::removeNode: Node 'TireBack_LOD300' has 1 objects attached, these will be reassigned to the node's parent ('null')
    TSShape::removeNode: Node 'collision-1' has 1 objects attached, these will be reassigned to the node's parent ('null')
    **\* LOADING MISSION: levels/Empty Terrain.mis
    **\* Stage 1 load
    **\* Stage 2 load
    Game -> activatePackages
    **\* Mission loaded
    Engine initialized...
    Sending heartbeat to master server [IP:198.101.240.242:28002]
    % 

Do I make something wrong, or my Graphics card is not supported ?

**Comment by eightyeight** [comment]
Just wanted to mention @raftakis, that we now pretty much have full support for Linux clients! Not sure how the build will go in Debian, but Ubuntu is supported, and apparently it's somewhat working in Fedora as well.
